project:
  type: book
  output-dir: docs

book:
  title: "PubPol 529: Coursebook"
  chapters:
    - index.qmd
    - chapter-1.qmd
    - chapter-2.qmd
    - chapter-3.qmd
    - chapter-4.qmd
    - chapter-5.qmd
    - chapter-6.qmd
    - chapter-7.qmd
    - chapter-8.qmd
    - chapter-9.qmd
    - chapter-10.qmd
    - chapter-11.qmd
    - chapter-12.qmd
    - chapter-13.qmd
    - chapter-14.qmd

format:
  html:
    theme: spacelab
    toc: true
    number-sections: true
    
execute:
  echo: true
  warning: false
  message: false
