<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>12&nbsp; Chapter 11: Association Between Categorical Variables – PubPol 529: Coursebook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter-12.html" rel="next">
<link href="./chapter-10.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e944e0e12dd6c2e1651c888e836d9b4b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter-11.html"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PubPol 529: Coursebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">PubPol 529: Coursebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 1: Measurement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 2: Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 3: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 5: Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 6: Sampling Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 7: Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 8: Significance Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 9: Experiments and Causality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-11.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 13: Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chapter 14: Linear Regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-i-independence-and-categorical-data" id="toc-part-i-independence-and-categorical-data" class="nav-link active" data-scroll-target="#part-i-independence-and-categorical-data"><span class="header-section-number">13</span> Part I: Independence and Categorical Data</a>
  <ul class="collapse">
  <li><a href="#from-probability-theory-to-chi-square-tests" id="toc-from-probability-theory-to-chi-square-tests" class="nav-link" data-scroll-target="#from-probability-theory-to-chi-square-tests"><span class="header-section-number">13.1</span> From Probability Theory to Chi-Square Tests</a></li>
  <li><a href="#example-gun-ownership-and-neighborhood-fear" id="toc-example-gun-ownership-and-neighborhood-fear" class="nav-link" data-scroll-target="#example-gun-ownership-and-neighborhood-fear"><span class="header-section-number">13.2</span> Example: Gun Ownership and Neighborhood Fear</a></li>
  <li><a href="#the-null-hypothesis-of-independence" id="toc-the-null-hypothesis-of-independence" class="nav-link" data-scroll-target="#the-null-hypothesis-of-independence"><span class="header-section-number">13.3</span> The Null Hypothesis of Independence</a></li>
  <li><a href="#expected-frequencies" id="toc-expected-frequencies" class="nav-link" data-scroll-target="#expected-frequencies"><span class="header-section-number">13.4</span> Expected Frequencies</a></li>
  <li><a href="#formula-for-expected-frequencies" id="toc-formula-for-expected-frequencies" class="nav-link" data-scroll-target="#formula-for-expected-frequencies"><span class="header-section-number">13.5</span> Formula for Expected Frequencies</a></li>
  <li><a href="#expected-frequencies-for-the-gun-ownership-example" id="toc-expected-frequencies-for-the-gun-ownership-example" class="nav-link" data-scroll-target="#expected-frequencies-for-the-gun-ownership-example"><span class="header-section-number">13.6</span> Expected Frequencies for the Gun Ownership Example</a></li>
  </ul></li>
  <li><a href="#part-ii-cross-tabulation-analysis" id="toc-part-ii-cross-tabulation-analysis" class="nav-link" data-scroll-target="#part-ii-cross-tabulation-analysis"><span class="header-section-number">14</span> Part II: Cross-Tabulation Analysis</a>
  <ul class="collapse">
  <li><a href="#contingency-tables-and-cross-tabs" id="toc-contingency-tables-and-cross-tabs" class="nav-link" data-scroll-target="#contingency-tables-and-cross-tabs"><span class="header-section-number">14.1</span> Contingency Tables and Cross-Tabs</a></li>
  <li><a href="#column-percentages" id="toc-column-percentages" class="nav-link" data-scroll-target="#column-percentages"><span class="header-section-number">14.2</span> Column Percentages</a></li>
  <li><a href="#adding-a-control-variable" id="toc-adding-a-control-variable" class="nav-link" data-scroll-target="#adding-a-control-variable"><span class="header-section-number">14.3</span> Adding a Control Variable</a></li>
  </ul></li>
  <li><a href="#part-iii-the-chi-square-test-of-independence" id="toc-part-iii-the-chi-square-test-of-independence" class="nav-link" data-scroll-target="#part-iii-the-chi-square-test-of-independence"><span class="header-section-number">15</span> Part III: The Chi-Square Test of Independence</a>
  <ul class="collapse">
  <li><a href="#assumptions-of-the-chi-square-test" id="toc-assumptions-of-the-chi-square-test" class="nav-link" data-scroll-target="#assumptions-of-the-chi-square-test"><span class="header-section-number">15.1</span> Assumptions of the Chi-Square Test</a></li>
  <li><a href="#the-chi-square-statistic" id="toc-the-chi-square-statistic" class="nav-link" data-scroll-target="#the-chi-square-statistic"><span class="header-section-number">15.2</span> The Chi-Square Statistic</a></li>
  <li><a href="#calculating-the-chi-square-statistic" id="toc-calculating-the-chi-square-statistic" class="nav-link" data-scroll-target="#calculating-the-chi-square-statistic"><span class="header-section-number">15.3</span> Calculating the Chi-Square Statistic</a></li>
  <li><a href="#degrees-of-freedom" id="toc-degrees-of-freedom" class="nav-link" data-scroll-target="#degrees-of-freedom"><span class="header-section-number">15.4</span> Degrees of Freedom</a></li>
  <li><a href="#the-chi-square-distribution" id="toc-the-chi-square-distribution" class="nav-link" data-scroll-target="#the-chi-square-distribution"><span class="header-section-number">15.5</span> The Chi-Square Distribution</a></li>
  <li><a href="#p-value-for-the-chi-square-test" id="toc-p-value-for-the-chi-square-test" class="nav-link" data-scroll-target="#p-value-for-the-chi-square-test"><span class="header-section-number">15.6</span> p-Value for the Chi-Square Test</a></li>
  <li><a href="#running-the-chi-square-test-in-software" id="toc-running-the-chi-square-test-in-software" class="nav-link" data-scroll-target="#running-the-chi-square-test-in-software"><span class="header-section-number">15.7</span> Running the Chi-Square Test in Software</a></li>
  </ul></li>
  <li><a href="#part-iv-example-program-and-graduation" id="toc-part-iv-example-program-and-graduation" class="nav-link" data-scroll-target="#part-iv-example-program-and-graduation"><span class="header-section-number">16</span> Part IV: Example: Program and Graduation</a>
  <ul class="collapse">
  <li><a href="#revisiting-the-graduation-program" id="toc-revisiting-the-graduation-program" class="nav-link" data-scroll-target="#revisiting-the-graduation-program"><span class="header-section-number">16.1</span> Revisiting the Graduation Program</a></li>
  <li><a href="#expected-frequencies-1" id="toc-expected-frequencies-1" class="nav-link" data-scroll-target="#expected-frequencies-1"><span class="header-section-number">16.2</span> Expected Frequencies</a></li>
  <li><a href="#chi-square-result" id="toc-chi-square-result" class="nav-link" data-scroll-target="#chi-square-result"><span class="header-section-number">16.3</span> Chi-Square Result</a></li>
  <li><a href="#relationship-between-z-and-chi-square-in-2-by-2-tables" id="toc-relationship-between-z-and-chi-square-in-2-by-2-tables" class="nav-link" data-scroll-target="#relationship-between-z-and-chi-square-in-2-by-2-tables"><span class="header-section-number">16.4</span> Relationship Between z and Chi-Square in 2-by-2 Tables</a></li>
  </ul></li>
  <li><a href="#part-v-example-satisfaction-with-aca-health-plans" id="toc-part-v-example-satisfaction-with-aca-health-plans" class="nav-link" data-scroll-target="#part-v-example-satisfaction-with-aca-health-plans"><span class="header-section-number">17</span> Part V: Example: Satisfaction with ACA Health Plans</a>
  <ul class="collapse">
  <li><a href="#the-research-question" id="toc-the-research-question" class="nav-link" data-scroll-target="#the-research-question"><span class="header-section-number">17.1</span> The Research Question</a></li>
  <li><a href="#observed-frequencies-and-column-percentages" id="toc-observed-frequencies-and-column-percentages" class="nav-link" data-scroll-target="#observed-frequencies-and-column-percentages"><span class="header-section-number">17.2</span> Observed Frequencies and Column Percentages</a></li>
  <li><a href="#expected-frequencies-2" id="toc-expected-frequencies-2" class="nav-link" data-scroll-target="#expected-frequencies-2"><span class="header-section-number">17.3</span> Expected Frequencies</a></li>
  <li><a href="#chi-square-statistic" id="toc-chi-square-statistic" class="nav-link" data-scroll-target="#chi-square-statistic"><span class="header-section-number">17.4</span> Chi-Square Statistic</a></li>
  <li><a href="#interpreting-the-result" id="toc-interpreting-the-result" class="nav-link" data-scroll-target="#interpreting-the-result"><span class="header-section-number">17.5</span> Interpreting the Result</a></li>
  </ul></li>
  <li><a href="#part-vi-residuals-and-cell-level-deviations" id="toc-part-vi-residuals-and-cell-level-deviations" class="nav-link" data-scroll-target="#part-vi-residuals-and-cell-level-deviations"><span class="header-section-number">18</span> Part VI: Residuals and Cell-Level Deviations</a>
  <ul class="collapse">
  <li><a href="#residuals" id="toc-residuals" class="nav-link" data-scroll-target="#residuals"><span class="header-section-number">18.1</span> Residuals</a></li>
  <li><a href="#residuals-in-the-aca-example" id="toc-residuals-in-the-aca-example" class="nav-link" data-scroll-target="#residuals-in-the-aca-example"><span class="header-section-number">18.2</span> Residuals in the ACA Example</a></li>
  <li><a href="#standardized-residuals" id="toc-standardized-residuals" class="nav-link" data-scroll-target="#standardized-residuals"><span class="header-section-number">18.3</span> Standardized Residuals</a></li>
  <li><a href="#example-standardized-residual" id="toc-example-standardized-residual" class="nav-link" data-scroll-target="#example-standardized-residual"><span class="header-section-number">18.4</span> Example: Standardized Residual</a></li>
  </ul></li>
  <li><a href="#part-vii-ordinal-variables-and-direction" id="toc-part-vii-ordinal-variables-and-direction" class="nav-link" data-scroll-target="#part-vii-ordinal-variables-and-direction"><span class="header-section-number">19</span> Part VII: Ordinal Variables and Direction</a>
  <ul class="collapse">
  <li><a href="#limits-of-chi-square-for-ordinal-data" id="toc-limits-of-chi-square-for-ordinal-data" class="nav-link" data-scroll-target="#limits-of-chi-square-for-ordinal-data"><span class="header-section-number">19.1</span> Limits of Chi-Square for Ordinal Data</a></li>
  <li><a href="#positive-and-negative-relationships" id="toc-positive-and-negative-relationships" class="nav-link" data-scroll-target="#positive-and-negative-relationships"><span class="header-section-number">19.2</span> Positive and Negative Relationships</a></li>
  <li><a href="#gamma-and-kendalls-tau-b" id="toc-gamma-and-kendalls-tau-b" class="nav-link" data-scroll-target="#gamma-and-kendalls-tau-b"><span class="header-section-number">19.3</span> Gamma and Kendall’s Tau-b</a></li>
  <li><a href="#example-spending-on-schools-and-social-security" id="toc-example-spending-on-schools-and-social-security" class="nav-link" data-scroll-target="#example-spending-on-schools-and-social-security"><span class="header-section-number">19.4</span> Example: Spending on Schools and Social Security</a></li>
  </ul></li>
  <li><a href="#part-viii-small-sample-tests" id="toc-part-viii-small-sample-tests" class="nav-link" data-scroll-target="#part-viii-small-sample-tests"><span class="header-section-number">20</span> Part VIII: Small-Sample Tests</a>
  <ul class="collapse">
  <li><a href="#when-chi-square-is-not-appropriate" id="toc-when-chi-square-is-not-appropriate" class="nav-link" data-scroll-target="#when-chi-square-is-not-appropriate"><span class="header-section-number">20.1</span> When Chi-Square Is Not Appropriate</a></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test"><span class="header-section-number">20.2</span> Fisher’s Exact Test</a></li>
  <li><a href="#fishers-exact-test-in-software" id="toc-fishers-exact-test-in-software" class="nav-link" data-scroll-target="#fishers-exact-test-in-software"><span class="header-section-number">20.3</span> Fisher’s Exact Test in Software</a></li>
  </ul></li>
  <li><a href="#part-ix-limitations-of-the-chi-square-test" id="toc-part-ix-limitations-of-the-chi-square-test" class="nav-link" data-scroll-target="#part-ix-limitations-of-the-chi-square-test"><span class="header-section-number">21</span> Part IX: Limitations of the Chi-Square Test</a>
  <ul class="collapse">
  <li><a href="#direction" id="toc-direction" class="nav-link" data-scroll-target="#direction"><span class="header-section-number">21.1</span> Direction</a></li>
  <li><a href="#magnitude" id="toc-magnitude" class="nav-link" data-scroll-target="#magnitude"><span class="header-section-number">21.2</span> Magnitude</a></li>
  <li><a href="#category-choices" id="toc-category-choices" class="nav-link" data-scroll-target="#category-choices"><span class="header-section-number">21.3</span> Category Choices</a></li>
  </ul></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">22</span> Key Terms</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">23</span> Chapter Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We now turn to statistical tests involving <strong>categorical variables</strong>.</p>
<p>Earlier, we studied difference-of-means tests, which require an interval-level outcome variable. We also studied difference-of-proportions tests, which compare two proportions across two groups. Those tests work well when the categorical variables are dichotomous: yes/no, treatment/control, Democrat/Republican, graduated/did not graduate, and so on.</p>
<p>But what if our variables have more than two categories?</p>
<p>For example:</p>
<ul>
<li>satisfaction with health insurance: satisfied, neutral, dissatisfied</li>
<li>political party: Democrat, Independent, Republican</li>
<li>policy opinion: decrease spending, keep it the same, increase spending</li>
<li>health insurance type: ACA exchange plan, employer plan, Medicare, Medicaid, uninsured</li>
<li>neighborhood fear: afraid, not afraid</li>
<li>gun ownership: owns a gun, does not own a gun</li>
</ul>
<p>When we have categorical data with multiple categories, we need a different tool. That tool is the <strong>chi-square test of independence</strong>.</p>
<p>A chi-square test asks whether two categorical variables are statistically independent. It compares the frequencies we actually observe in a table to the frequencies we would expect to see if the variables were independent.</p>
<p>This chapter introduces cross-tabulation analysis, expected frequencies, the chi-square statistic, the chi-square distribution, residuals, and methods for assessing the direction and magnitude of relationships among categorical variables. We also discuss Fisher’s exact test for small samples.</p>
<hr>
<section id="part-i-independence-and-categorical-data" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Part I: Independence and Categorical Data</h1>
<section id="from-probability-theory-to-chi-square-tests" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="from-probability-theory-to-chi-square-tests"><span class="header-section-number">13.1</span> From Probability Theory to Chi-Square Tests</h2>
<p>Earlier, we defined independence using conditional probabilities.</p>
<p>Two events <span class="math inline">\(A\)</span> and <span class="math inline">\(B\)</span> are independent if:</p>
<p><span class="math display">\[
P(A \mid B) = P(A)
\]</span></p>
<p>In words: knowing that <span class="math inline">\(B\)</span> occurred does not change the probability of <span class="math inline">\(A\)</span>.</p>
<p>The same logic applies to categorical variables.</p>
<p>Suppose we have two categorical variables:</p>
<ul>
<li><span class="math inline">\(Y\)</span>: whether someone owns a gun</li>
<li><span class="math inline">\(X\)</span>: whether someone is afraid to walk in their neighborhood at night</li>
</ul>
<p>If these variables are independent, then the probability of owning a gun should be the same whether or not someone is afraid to walk in their neighborhood.</p>
<p>That is:</p>
<p><span class="math display">\[
P(\text{Owns gun} \mid \text{Afraid}) =
P(\text{Owns gun})
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
P(\text{Owns gun} \mid \text{Not afraid}) =
P(\text{Owns gun})
\]</span></p>
<p>If those conditional probabilities differ, the variables are not independent.</p>
<p>But sample data always contain random sampling error. We need to know whether the differences we observe are large enough to reject independence with statistical confidence.</p>
<p>That is what the chi-square test does.</p>
<hr>
</section>
<section id="example-gun-ownership-and-neighborhood-fear" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="example-gun-ownership-and-neighborhood-fear"><span class="header-section-number">13.2</span> Example: Gun Ownership and Neighborhood Fear</h2>
<p>Suppose the General Social Survey asks two questions:</p>
<ol type="1">
<li>Do you own a gun?</li>
<li>Are you afraid to walk in your neighborhood at night?</li>
</ol>
<p>The joint frequency distribution is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid</th>
<th style="text-align: right;">Not Afraid</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">528</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">707</td>
<td style="text-align: right;">1,120</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>546</strong></td>
<td style="text-align: right;"><strong>1,102</strong></td>
<td style="text-align: right;"><strong>1,648</strong></td>
</tr>
</tbody>
</table>
<p>Overall, the proportion who own a gun is:</p>
<p><span class="math display">\[
\frac{528}{1648} = 0.3204
\]</span></p>
<p>So about 32.04 percent of respondents own a gun.</p>
<p>Among people who are afraid to walk in their neighborhood at night, the proportion who own a gun is:</p>
<p><span class="math display">\[
\frac{133}{546} = 0.2436
\]</span></p>
<p>Among people who are not afraid, the proportion who own a gun is:</p>
<p><span class="math display">\[
\frac{395}{1102} = 0.3584
\]</span></p>
<p>These conditional probabilities differ from the unconditional probability of 0.3204.</p>
<p>That suggests the variables may not be independent.</p>
<p>But we need a statistical test to determine whether the deviation is large enough to reject the null hypothesis of independence.</p>
<hr>
</section>
<section id="the-null-hypothesis-of-independence" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="the-null-hypothesis-of-independence"><span class="header-section-number">13.3</span> The Null Hypothesis of Independence</h2>
<p>For a chi-square test of independence, the null hypothesis is:</p>
<p><span class="math display">\[
H_0: X \text{ and } Y \text{ are independent}
\]</span></p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[
H_A: X \text{ and } Y \text{ are not independent}
\]</span></p>
<p>In words:</p>
<ul>
<li>The null hypothesis says the distribution of <span class="math inline">\(Y\)</span> does not depend on <span class="math inline">\(X\)</span>.</li>
<li>The alternative hypothesis says the distribution of <span class="math inline">\(Y\)</span> does depend on <span class="math inline">\(X\)</span>.</li>
</ul>
<p>In the gun ownership example:</p>
<p><span class="math display">\[
H_0:
\text{Gun ownership and fear of walking at night are independent}
\]</span></p>
<p><span class="math display">\[
H_A:
\text{Gun ownership and fear of walking at night are not independent}
\]</span></p>
<hr>
</section>
<section id="expected-frequencies" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="expected-frequencies"><span class="header-section-number">13.4</span> Expected Frequencies</h2>
<p>The chi-square test compares observed frequencies to expected frequencies.</p>
<p>An <strong>observed frequency</strong> is the number we actually see in the data.</p>
<p>An <strong>expected frequency</strong> is the number we would expect to see if the null hypothesis of independence were true.</p>
<p>For example, we observed 133 people who both:</p>
<ul>
<li>own a gun</li>
<li>are afraid to walk in their neighborhood at night</li>
</ul>
<p>But if gun ownership and neighborhood fear were independent, how many would we expect in that cell?</p>
<p>The overall gun ownership rate is 0.3204. If independence holds, then 32.04 percent of people in every fear category should own a gun.</p>
<p>There are 546 people who are afraid. So the expected frequency is:</p>
<p><span class="math display">\[
546(0.3204) = 174.9
\]</span></p>
<p>So under independence, we would expect about 174.9 afraid respondents to own a gun.</p>
<p>We observed only 133.</p>
<p>That difference contributes to the chi-square statistic.</p>
<hr>
</section>
<section id="formula-for-expected-frequencies" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="formula-for-expected-frequencies"><span class="header-section-number">13.5</span> Formula for Expected Frequencies</h2>
<p>For any cell in a contingency table, the expected frequency is:</p>
<p><span class="math display">\[
f_e =
\frac{(\text{row total})(\text{column total})}{n}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(f_e\)</span> is the expected frequency</li>
<li><span class="math inline">\(n\)</span> is the total sample size</li>
</ul>
<p>For the “owns gun” and “afraid” cell:</p>
<p><span class="math display">\[
f_e =
\frac{(528)(546)}{1648}
\]</span></p>
<p><span class="math display">\[
f_e = 174.9
\]</span></p>
<p>This formula works for every cell in the table.</p>
<hr>
</section>
<section id="expected-frequencies-for-the-gun-ownership-example" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="expected-frequencies-for-the-gun-ownership-example"><span class="header-section-number">13.6</span> Expected Frequencies for the Gun Ownership Example</h2>
<p>Using the formula, the expected frequencies are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid</th>
<th style="text-align: right;">Not Afraid</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">174.9</td>
<td style="text-align: right;">353.1</td>
<td style="text-align: right;">528</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">371.1</td>
<td style="text-align: right;">748.9</td>
<td style="text-align: right;">1,120</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>546</strong></td>
<td style="text-align: right;"><strong>1,102</strong></td>
<td style="text-align: right;"><strong>1,648</strong></td>
</tr>
</tbody>
</table>
<p>These are the frequencies we would expect if gun ownership and fear of walking at night were independent.</p>
<p>The observed frequencies were:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid</th>
<th style="text-align: right;">Not Afraid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">395</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">707</td>
</tr>
</tbody>
</table>
<p>The chi-square statistic summarizes how far the observed frequencies deviate from the expected frequencies.</p>
<hr>
</section>
</section>
<section id="part-ii-cross-tabulation-analysis" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Part II: Cross-Tabulation Analysis</h1>
<section id="contingency-tables-and-cross-tabs" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="contingency-tables-and-cross-tabs"><span class="header-section-number">14.1</span> Contingency Tables and Cross-Tabs</h2>
<p>A <strong>contingency table</strong>, also called a <strong>cross-tabulation</strong> or <strong>cross-tab</strong>, displays the joint distribution of two categorical variables.</p>
<p>Cross-tabs are useful for examining whether the distribution of one variable changes across categories of another variable.</p>
<p>When constructing these tables, it is often clearest to put:</p>
<ul>
<li>the dependent variable <span class="math inline">\(Y\)</span> in the rows</li>
<li>the independent variable <span class="math inline">\(X\)</span> in the columns</li>
</ul>
<p>This makes it easy to compare column percentages side by side.</p>
<p>For example:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Dependent Variable <span class="math inline">\(Y\)</span></th>
<th style="text-align: right;"><span class="math inline">\(X=1\)</span></th>
<th style="text-align: right;"><span class="math inline">\(X=2\)</span></th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Category 1</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
</tr>
<tr class="even">
<td>Category 2</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
</tr>
<tr class="odd">
<td>Category 3</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">100%</td>
<td style="text-align: right;">100%</td>
</tr>
</tbody>
</table>
<p>Column percentages allow us to ask:</p>
<blockquote class="blockquote">
<p>Does the distribution of <span class="math inline">\(Y\)</span> change as we move across categories of <span class="math inline">\(X\)</span>?</p>
</blockquote>
<hr>
</section>
<section id="column-percentages" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="column-percentages"><span class="header-section-number">14.2</span> Column Percentages</h2>
<p>Using the gun ownership example:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid</th>
<th style="text-align: right;">Not Afraid</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">24.36%</td>
<td style="text-align: right;">35.84%</td>
<td style="text-align: right;">32.04%</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">75.64%</td>
<td style="text-align: right;">64.16%</td>
<td style="text-align: right;">67.96%</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">100.00%</td>
<td style="text-align: right;">100.00%</td>
<td style="text-align: right;">100.00%</td>
</tr>
</tbody>
</table>
<p>These column percentages show that gun ownership is lower among those who say they are afraid to walk in their neighborhood at night.</p>
<p>Among those afraid:</p>
<p><span class="math display">\[
24.36\%
\]</span></p>
<p>own guns.</p>
<p>Among those not afraid:</p>
<p><span class="math display">\[
35.84\%
\]</span></p>
<p>own guns.</p>
<p>If the variables were independent, both column percentages would equal the overall gun ownership rate:</p>
<p><span class="math display">\[
32.04\%
\]</span></p>
<p>They do not. The chi-square test tells us whether the observed deviation is statistically significant.</p>
<hr>
</section>
<section id="adding-a-control-variable" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="adding-a-control-variable"><span class="header-section-number">14.3</span> Adding a Control Variable</h2>
<p>We can add a control variable to a cross-tabulation.</p>
<p>Suppose we add whether someone hunts.</p>
<p>Hunting is likely related to gun ownership. Hunters are much more likely to own guns than non-hunters.</p>
<p>If we control for hunting, we compare gun ownership and neighborhood fear separately among:</p>
<ul>
<li>non-hunters</li>
<li>hunters</li>
</ul>
<p>This creates separate cross-tabs within each category of the control variable.</p>
<p>For example:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid, Non-Hunter</th>
<th style="text-align: right;">Not Afraid, Non-Hunter</th>
<th style="text-align: right;">Afraid, Hunter</th>
<th style="text-align: right;">Not Afraid, Hunter</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
<td style="text-align: right;">%</td>
</tr>
</tbody>
</table>
<p>If fear of walking at night is related to gun ownership only among non-hunters but not among hunters, then the control variable helps refine the relationship.</p>
<p>This is similar to controlled mean comparisons. We hold a third variable constant to see whether the relationship between <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> persists.</p>
<p>However, cross-tabs can become unwieldy quickly when we add more variables or categories. This is one reason regression methods become useful.</p>
<hr>
</section>
</section>
<section id="part-iii-the-chi-square-test-of-independence" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Part III: The Chi-Square Test of Independence</h1>
<section id="assumptions-of-the-chi-square-test" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="assumptions-of-the-chi-square-test"><span class="header-section-number">15.1</span> Assumptions of the Chi-Square Test</h2>
<p>The chi-square test of independence requires:</p>
<ol type="1">
<li>A random or representative sample.</li>
<li>Two categorical variables.</li>
<li>Mutually exclusive categories.</li>
<li>Expected frequencies of at least 5 in every cell.</li>
</ol>
<p>The expected frequency condition is important.</p>
<p>It refers to expected frequencies, not observed frequencies.</p>
<p>If expected frequencies are too small, the chi-square approximation may not be reliable. In that case, Fisher’s exact test may be preferable.</p>
<hr>
</section>
<section id="the-chi-square-statistic" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="the-chi-square-statistic"><span class="header-section-number">15.2</span> The Chi-Square Statistic</h2>
<p>The chi-square statistic is:</p>
<p><span class="math display">\[
\chi^2 =
\sum
\frac{(f_o - f_e)^2}{f_e}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(f_o\)</span> is the observed frequency</li>
<li><span class="math inline">\(f_e\)</span> is the expected frequency</li>
<li>the sum is taken across all cells in the table</li>
</ul>
<p>The statistic measures how far observed frequencies are from expected frequencies.</p>
<p>If observed and expected frequencies are identical, then:</p>
<p><span class="math display">\[
f_o - f_e = 0
\]</span></p>
<p>for every cell, and:</p>
<p><span class="math display">\[
\chi^2 = 0
\]</span></p>
<p>As observed frequencies deviate more from expected frequencies, the chi-square statistic grows larger.</p>
<hr>
</section>
<section id="calculating-the-chi-square-statistic" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="calculating-the-chi-square-statistic"><span class="header-section-number">15.3</span> Calculating the Chi-Square Statistic</h2>
<p>For the gun ownership example, the observed and expected values are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Owns Gun</th>
<th style="text-align: right;">Afraid Observed</th>
<th style="text-align: right;">Afraid Expected</th>
<th style="text-align: right;">Not Afraid Observed</th>
<th style="text-align: right;">Not Afraid Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Yes</td>
<td style="text-align: right;">133</td>
<td style="text-align: right;">174.9</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">353.1</td>
</tr>
<tr class="even">
<td>No</td>
<td style="text-align: right;">413</td>
<td style="text-align: right;">371.1</td>
<td style="text-align: right;">707</td>
<td style="text-align: right;">748.9</td>
</tr>
</tbody>
</table>
<p>For each cell, calculate:</p>
<p><span class="math display">\[
\frac{(f_o - f_e)^2}{f_e}
\]</span></p>
<p>For the “owns gun and afraid” cell:</p>
<p><span class="math display">\[
\frac{(133 - 174.9)^2}{174.9}
\]</span></p>
<p><span class="math display">\[
= \frac{(-41.9)^2}{174.9}
\]</span></p>
<p><span class="math display">\[
\approx 10.1
\]</span></p>
<p>Repeat for each cell:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Cell</th>
<th style="text-align: right;">Contribution to <span class="math inline">\(\chi^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Owns gun, afraid</td>
<td style="text-align: right;">10.1</td>
</tr>
<tr class="even">
<td>Owns gun, not afraid</td>
<td style="text-align: right;">5.0</td>
</tr>
<tr class="odd">
<td>Does not own gun, afraid</td>
<td style="text-align: right;">4.7</td>
</tr>
<tr class="even">
<td>Does not own gun, not afraid</td>
<td style="text-align: right;">2.4</td>
</tr>
</tbody>
</table>
<p>Add them:</p>
<p><span class="math display">\[
\chi^2 = 10.1 + 5.0 + 4.7 + 2.4
\]</span></p>
<p><span class="math display">\[
\chi^2 = 22.2
\]</span></p>
<hr>
</section>
<section id="degrees-of-freedom" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="degrees-of-freedom"><span class="header-section-number">15.4</span> Degrees of Freedom</h2>
<p>For a chi-square test of independence:</p>
<p><span class="math display">\[
df = (r-1)(c-1)
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(r\)</span> is the number of rows</li>
<li><span class="math inline">\(c\)</span> is the number of columns</li>
</ul>
<p>Do not count total rows or total columns.</p>
<p>In the gun ownership example, there are:</p>
<ul>
<li>2 rows</li>
<li>2 columns</li>
</ul>
<p>So:</p>
<p><span class="math display">\[
df = (2-1)(2-1)
\]</span></p>
<p><span class="math display">\[
df = 1
\]</span></p>
<hr>
</section>
<section id="the-chi-square-distribution" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="the-chi-square-distribution"><span class="header-section-number">15.5</span> The Chi-Square Distribution</h2>
<p>The chi-square distribution is different from the normal and t distributions.</p>
<p>It starts at 0 and extends to positive infinity.</p>
<p>A chi-square statistic can never be negative.</p>
<p>A chi-square test is therefore a <strong>one-sided test</strong>. We reject the null hypothesis only for large values of <span class="math inline">\(\chi^2\)</span>.</p>
<p>For <span class="math inline">\(\alpha = 0.05\)</span> and <span class="math inline">\(df = 1\)</span>, the critical value is:</p>
<p><span class="math display">\[
\chi^2 = 3.84
\]</span></p>
<p>Our test statistic is:</p>
<p><span class="math display">\[
\chi^2 = 22.2
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
22.2 &gt; 3.84
\]</span></p>
<p>we reject the null hypothesis.</p>
<p>Gun ownership and fear of walking in one’s neighborhood at night are not independent.</p>
<hr>
</section>
<section id="p-value-for-the-chi-square-test" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="p-value-for-the-chi-square-test"><span class="header-section-number">15.6</span> p-Value for the Chi-Square Test</h2>
<p>The p-value is the area in the upper tail of the chi-square distribution beyond the observed chi-square statistic.</p>
<p>Unlike two-tailed t-tests and z-tests, we do not double the p-value.</p>
<p>For the gun ownership example, the test statistic is so large that:</p>
<p><span class="math display">\[
p &lt; 0.001
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
p &lt; 0.05
\]</span></p>
<p>we reject the null hypothesis.</p>
<hr>
</section>
<section id="running-the-chi-square-test-in-software" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="running-the-chi-square-test-in-software"><span class="header-section-number">15.7</span> Running the Chi-Square Test in Software</h2>
<p>In Stata, the command structure is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">tab</span> yvar xvar, col chi</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This produces a cross-tabulation with column percentages and a chi-square test.</p>
<p>In R, one common workflow is:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>mytable <span class="ot">&lt;-</span> <span class="fu">table</span>(yvar, xvar)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(mytable, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The argument <code>correct = FALSE</code> avoids a small-sample correction that is not needed for large samples.</p>
<p>Software reports:</p>
<ul>
<li>chi-square statistic</li>
<li>degrees of freedom</li>
<li>p-value</li>
</ul>
<hr>
</section>
</section>
<section id="part-iv-example-program-and-graduation" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> Part IV: Example: Program and Graduation</h1>
<section id="revisiting-the-graduation-program" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="revisiting-the-graduation-program"><span class="header-section-number">16.1</span> Revisiting the Graduation Program</h2>
<p>Earlier, we analyzed a difference of proportions for a program intended to increase high school graduation.</p>
<p>The data were:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Graduated</th>
<th style="text-align: right;">Did Not Graduate</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Program</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">93</td>
</tr>
<tr class="even">
<td>No Program</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">121</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">214</td>
</tr>
</tbody>
</table>
<p>The graduation rates were:</p>
<p><span class="math display">\[
\frac{83}{93} = 0.892
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
\frac{102}{121} = 0.843
\]</span></p>
<p>The difference was not statistically significant using a z-test.</p>
<p>We can also analyze this as a chi-square test because it is a 2-by-2 table.</p>
<hr>
</section>
<section id="expected-frequencies-1" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="expected-frequencies-1"><span class="header-section-number">16.2</span> Expected Frequencies</h2>
<p>The overall graduation rate is:</p>
<p><span class="math display">\[
\frac{185}{214} = 0.864
\]</span></p>
<p>If program participation and graduation were independent, we would expect 86.4 percent of each group to graduate.</p>
<p>The expected frequencies are approximately:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Graduated Expected</th>
<th style="text-align: right;">Did Not Graduate Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Program</td>
<td style="text-align: right;">80.4</td>
<td style="text-align: right;">12.6</td>
</tr>
<tr class="even">
<td>No Program</td>
<td style="text-align: right;">104.6</td>
<td style="text-align: right;">16.4</td>
</tr>
</tbody>
</table>
<p>All expected frequencies exceed 5, so the chi-square test is appropriate.</p>
<hr>
</section>
<section id="chi-square-result" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="chi-square-result"><span class="header-section-number">16.3</span> Chi-Square Result</h2>
<p>Using the formula:</p>
<p><span class="math display">\[
\chi^2 =
\sum
\frac{(f_o - f_e)^2}{f_e}
\]</span></p>
<p>we obtain:</p>
<p><span class="math display">\[
\chi^2 = 1.10
\]</span></p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df = (2-1)(2-1)=1
\]</span></p>
<p>The critical value at <span class="math inline">\(\alpha = 0.05\)</span> is:</p>
<p><span class="math display">\[
3.84
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
1.10 &lt; 3.84
\]</span></p>
<p>we fail to reject the null hypothesis.</p>
<p>The chi-square test reaches the same conclusion as the difference-of-proportions z-test.</p>
<hr>
</section>
<section id="relationship-between-z-and-chi-square-in-2-by-2-tables" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="relationship-between-z-and-chi-square-in-2-by-2-tables"><span class="header-section-number">16.4</span> Relationship Between z and Chi-Square in 2-by-2 Tables</h2>
<p>For a 2-by-2 table, the chi-square statistic with one degree of freedom is equal to the square of the z-statistic from the difference-of-proportions test:</p>
<p><span class="math display">\[
\chi^2 = z^2
\]</span></p>
<p>In the graduation example, the z-statistic was:</p>
<p><span class="math display">\[
z = 1.049
\]</span></p>
<p>Squaring it:</p>
<p><span class="math display">\[
1.049^2 \approx 1.10
\]</span></p>
<p>which equals the chi-square statistic.</p>
<p>This relationship holds only for 2-by-2 tables.</p>
<p>Once one of the variables has more than two categories, the chi-square test no longer reduces to a z-test.</p>
<hr>
</section>
</section>
<section id="part-v-example-satisfaction-with-aca-health-plans" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Part V: Example: Satisfaction with ACA Health Plans</h1>
<section id="the-research-question" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="the-research-question"><span class="header-section-number">17.1</span> The Research Question</h2>
<p>Suppose we want to analyze satisfaction with health insurance plans after implementation of the Affordable Care Act.</p>
<p>The dependent variable is satisfaction with one’s health plan:</p>
<ul>
<li>satisfied</li>
<li>neutral</li>
<li>dissatisfied</li>
</ul>
<p>The independent variable is type of health insurance:</p>
<ul>
<li>ACA exchange plan</li>
<li>other health insurance</li>
</ul>
<p>The question is:</p>
<blockquote class="blockquote">
<p>Is satisfaction with one’s health insurance independent of plan type?</p>
</blockquote>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \text{Satisfaction and plan type are independent}
\]</span></p>
<p>The alternative is:</p>
<p><span class="math display">\[
H_A: \text{Satisfaction and plan type are not independent}
\]</span></p>
<hr>
</section>
<section id="observed-frequencies-and-column-percentages" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="observed-frequencies-and-column-percentages"><span class="header-section-number">17.2</span> Observed Frequencies and Column Percentages</h2>
<p>Suppose the data are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Satisfaction</th>
<th style="text-align: right;">ACA Plan</th>
<th style="text-align: right;">Other Plan</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Satisfied</td>
<td style="text-align: right;">772</td>
<td style="text-align: right;">5,096</td>
<td style="text-align: right;">5,868</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">895</td>
<td style="text-align: right;">1,100</td>
</tr>
<tr class="odd">
<td>Dissatisfied</td>
<td style="text-align: right;">108</td>
<td style="text-align: right;">386</td>
<td style="text-align: right;">494</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>1,085</strong></td>
<td style="text-align: right;"><strong>6,377</strong></td>
<td style="text-align: right;"><strong>7,462</strong></td>
</tr>
</tbody>
</table>
<p>Column percentages show:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Satisfaction</th>
<th style="text-align: right;">ACA Plan</th>
<th style="text-align: right;">Other Plan</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Satisfied</td>
<td style="text-align: right;">71.2%</td>
<td style="text-align: right;">79.9%</td>
<td style="text-align: right;">78.6%</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td style="text-align: right;">18.9%</td>
<td style="text-align: right;">14.0%</td>
<td style="text-align: right;">14.7%</td>
</tr>
<tr class="odd">
<td>Dissatisfied</td>
<td style="text-align: right;">10.0%</td>
<td style="text-align: right;">6.1%</td>
<td style="text-align: right;">6.7%</td>
</tr>
</tbody>
</table>
<p>People with ACA exchange plans are less likely to report being satisfied and more likely to report being neutral or dissatisfied.</p>
<p>Now we test whether this relationship is statistically significant.</p>
<hr>
</section>
<section id="expected-frequencies-2" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="expected-frequencies-2"><span class="header-section-number">17.3</span> Expected Frequencies</h2>
<p>Under independence, the satisfaction distribution should be the same for ACA plans and other plans.</p>
<p>For example, 78.6 percent of all respondents are satisfied. If plan type does not matter, then 78.6 percent of ACA respondents and 78.6 percent of other-plan respondents should be satisfied.</p>
<p>Using:</p>
<p><span class="math display">\[
f_e = \frac{(\text{row total})(\text{column total})}{n}
\]</span></p>
<p>the expected frequencies are approximately:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Satisfaction</th>
<th style="text-align: right;">ACA Expected</th>
<th style="text-align: right;">Other Expected</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Satisfied</td>
<td style="text-align: right;">853.2</td>
<td style="text-align: right;">5,014.8</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td style="text-align: right;">159.9</td>
<td style="text-align: right;">940.1</td>
</tr>
<tr class="odd">
<td>Dissatisfied</td>
<td style="text-align: right;">71.9</td>
<td style="text-align: right;">422.1</td>
</tr>
</tbody>
</table>
<p>All expected frequencies exceed 5, so the chi-square test is appropriate.</p>
<hr>
</section>
<section id="chi-square-statistic" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="chi-square-statistic"><span class="header-section-number">17.4</span> Chi-Square Statistic</h2>
<p>For each cell:</p>
<p><span class="math display">\[
\frac{(f_o - f_e)^2}{f_e}
\]</span></p>
<p>The contributions are approximately:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Satisfaction</th>
<th style="text-align: right;">ACA Contribution</th>
<th style="text-align: right;">Other Contribution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Satisfied</td>
<td style="text-align: right;">7.7</td>
<td style="text-align: right;">1.3</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td style="text-align: right;">12.7</td>
<td style="text-align: right;">2.2</td>
</tr>
<tr class="odd">
<td>Dissatisfied</td>
<td style="text-align: right;">18.1</td>
<td style="text-align: right;">3.1</td>
</tr>
</tbody>
</table>
<p>Adding all cell contributions gives:</p>
<p><span class="math display">\[
\chi^2 \approx 45.1
\]</span></p>
<p>Using the lecture’s rounded values, the statistic was reported around:</p>
<p><span class="math display">\[
\chi^2 \approx 50.4
\]</span></p>
<p>Small differences can arise from rounding or slightly different underlying cell values. The substantive conclusion is the same: the statistic is very large.</p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df = (3-1)(2-1)
\]</span></p>
<p><span class="math display">\[
df = 2
\]</span></p>
<p>At <span class="math inline">\(\alpha = 0.05\)</span>, the critical value for <span class="math inline">\(df=2\)</span> is:</p>
<p><span class="math display">\[
5.99
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
50.4 &gt; 5.99
\]</span></p>
<p>we reject the null hypothesis.</p>
<p>Satisfaction and plan type are not independent.</p>
<hr>
</section>
<section id="interpreting-the-result" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="interpreting-the-result"><span class="header-section-number">17.5</span> Interpreting the Result</h2>
<p>The chi-square test tells us that satisfaction differs by plan type.</p>
<p>But the chi-square statistic itself does not tell us the direction of the relationship.</p>
<p>To interpret direction, we must examine the table.</p>
<p>ACA exchange plan respondents are:</p>
<ul>
<li>less likely to be satisfied</li>
<li>more likely to be neutral</li>
<li>more likely to be dissatisfied</li>
</ul>
<p>The chi-square test tells us the relationship is statistically significant. The table tells us what the relationship looks like.</p>
<hr>
</section>
</section>
<section id="part-vi-residuals-and-cell-level-deviations" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Part VI: Residuals and Cell-Level Deviations</h1>
<section id="residuals" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="residuals"><span class="header-section-number">18.1</span> Residuals</h2>
<p>A <strong>residual</strong> in a chi-square table is:</p>
<p><span class="math display">\[
f_o - f_e
\]</span></p>
<p>It tells us whether a cell contains more or fewer cases than expected under independence.</p>
<p>A positive residual means:</p>
<p><span class="math display">\[
f_o &gt; f_e
\]</span></p>
<p>There are more cases in that cell than expected.</p>
<p>A negative residual means:</p>
<p><span class="math display">\[
f_o &lt; f_e
\]</span></p>
<p>There are fewer cases in that cell than expected.</p>
<p>Residuals help us understand the direction of the relationship.</p>
<hr>
</section>
<section id="residuals-in-the-aca-example" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="residuals-in-the-aca-example"><span class="header-section-number">18.2</span> Residuals in the ACA Example</h2>
<p>For the ACA satisfaction example:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Satisfaction</th>
<th style="text-align: right;">ACA Residual</th>
<th style="text-align: right;">Other Residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Satisfied</td>
<td style="text-align: right;">negative</td>
<td style="text-align: right;">positive</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td style="text-align: right;">positive</td>
<td style="text-align: right;">negative</td>
</tr>
<tr class="odd">
<td>Dissatisfied</td>
<td style="text-align: right;">positive</td>
<td style="text-align: right;">negative</td>
</tr>
</tbody>
</table>
<p>This means:</p>
<ul>
<li>fewer ACA plan respondents are satisfied than expected</li>
<li>more ACA plan respondents are neutral than expected</li>
<li>more ACA plan respondents are dissatisfied than expected</li>
</ul>
<p>The opposite pattern appears among respondents with other health insurance.</p>
<hr>
</section>
<section id="standardized-residuals" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="standardized-residuals"><span class="header-section-number">18.3</span> Standardized Residuals</h2>
<p>A raw residual can be hard to interpret because its size depends on the sample size and expected frequency.</p>
<p>We can convert residuals into standardized residuals, which function like z-statistics.</p>
<p>A standardized residual is:</p>
<p><span class="math display">\[
z =
\frac{f_o - f_e}
{
\sqrt{
f_e(1-p_{row})(1-p_{column})
}
}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(p_{row}\)</span> is the row proportion</li>
<li><span class="math inline">\(p_{column}\)</span> is the column proportion</li>
</ul>
<p>Large positive or negative standardized residuals indicate cells that contribute strongly to the chi-square statistic.</p>
<p>A standardized residual beyond approximately <span class="math inline">\(\pm 1.96\)</span> suggests that the cell deviation is large relative to what we would expect under independence.</p>
<hr>
</section>
<section id="example-standardized-residual" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="example-standardized-residual"><span class="header-section-number">18.4</span> Example: Standardized Residual</h2>
<p>Suppose the ACA-satisfied cell has:</p>
<p><span class="math display">\[
f_o = 772
\]</span></p>
<p><span class="math display">\[
f_e = 853.2
\]</span></p>
<p>The residual is:</p>
<p><span class="math display">\[
772 - 853.2 = -81.2
\]</span></p>
<p>If the standardized residual is:</p>
<p><span class="math display">\[
z = -6.50
\]</span></p>
<p>that is a very large negative deviation.</p>
<p>This means the ACA-satisfied cell has far fewer cases than expected under independence.</p>
<p>The result is not merely statistically significant overall. This specific cell is contributing strongly to the relationship.</p>
<hr>
</section>
</section>
<section id="part-vii-ordinal-variables-and-direction" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> Part VII: Ordinal Variables and Direction</h1>
<section id="limits-of-chi-square-for-ordinal-data" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="limits-of-chi-square-for-ordinal-data"><span class="header-section-number">19.1</span> Limits of Chi-Square for Ordinal Data</h2>
<p>The chi-square test treats categories as nominal.</p>
<p>It does not care whether categories have a meaningful order.</p>
<p>For example, if a variable has categories:</p>
<ul>
<li>decrease</li>
<li>keep the same</li>
<li>increase</li>
</ul>
<p>the chi-square test treats them simply as three categories. It does not know that “increase” is higher than “keep the same” or that “decrease” is lower.</p>
<p>This is a limitation when variables are ordinal.</p>
<p>If both variables are ordinal, we may want to know whether the relationship is positive or negative.</p>
<p>The chi-square test does not provide that.</p>
<hr>
</section>
<section id="positive-and-negative-relationships" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="positive-and-negative-relationships"><span class="header-section-number">19.2</span> Positive and Negative Relationships</h2>
<p>A <strong>positive relationship</strong> between two ordinal variables means higher values of one variable tend to be associated with higher values of the other variable.</p>
<p>A <strong>negative relationship</strong> means higher values of one variable tend to be associated with lower values of the other variable.</p>
<p>For example, suppose one variable measures support for legalizing marijuana:</p>
<ul>
<li>oppose</li>
<li>neutral</li>
<li>favor</li>
</ul>
<p>and another measures whether gun laws should be more restrictive:</p>
<ul>
<li>make it more difficult to buy a gun</li>
<li>keep laws the same</li>
<li>make it easier to buy a gun</li>
</ul>
<p>If people who favor marijuana legalization also tend to favor more restrictive gun laws, the relationship may be negative depending on how the categories are ordered.</p>
<p>Direction depends on category coding.</p>
<p>Always check which direction the categories move.</p>
<hr>
</section>
<section id="gamma-and-kendalls-tau-b" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="gamma-and-kendalls-tau-b"><span class="header-section-number">19.3</span> Gamma and Kendall’s Tau-b</h2>
<p>For ordinal variables, we can use measures such as:</p>
<ul>
<li>Goodman and Kruskal’s gamma</li>
<li>Kendall’s tau-b</li>
</ul>
<p>These statistics can be positive, negative, or close to zero.</p>
<p>Interpretation:</p>
<ul>
<li>positive value: variables tend to move in the same direction</li>
<li>negative value: variables tend to move in opposite directions</li>
<li>near zero: little ordinal association</li>
</ul>
<p>These statistics supplement the chi-square test by describing the direction of the ordinal relationship.</p>
<p>For example, if gamma is:</p>
<p><span class="math display">\[
-0.35
\]</span></p>
<p>then the relationship is negative.</p>
<p>If gamma is:</p>
<p><span class="math display">\[
0.42
\]</span></p>
<p>then the relationship is positive.</p>
<p>These values also have standard errors, allowing assessment of whether they are meaningfully different from zero.</p>
<hr>
</section>
<section id="example-spending-on-schools-and-social-security" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="example-spending-on-schools-and-social-security"><span class="header-section-number">19.4</span> Example: Spending on Schools and Social Security</h2>
<p>Suppose respondents are asked whether federal spending on public schools should:</p>
<ul>
<li>decrease</li>
<li>stay the same</li>
<li>increase</li>
</ul>
<p>and whether spending on Social Security should:</p>
<ul>
<li>decrease</li>
<li>stay the same</li>
<li>increase</li>
</ul>
<p>We might expect a positive relationship. People who favor more spending in one area may also favor more spending in another.</p>
<p>If gamma and Kendall’s tau-b are positive and large relative to their standard errors, that supports the interpretation of a positive ordinal relationship.</p>
<p>The chi-square test tells us whether the variables are independent.</p>
<p>Gamma and tau-b help tell us the direction.</p>
<hr>
</section>
</section>
<section id="part-viii-small-sample-tests" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Part VIII: Small-Sample Tests</h1>
<section id="when-chi-square-is-not-appropriate" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="when-chi-square-is-not-appropriate"><span class="header-section-number">20.1</span> When Chi-Square Is Not Appropriate</h2>
<p>The chi-square test requires expected frequencies of at least 5 in every cell.</p>
<p>If this condition fails, the chi-square approximation may be unreliable.</p>
<p>In such cases, use Fisher’s exact test.</p>
<hr>
</section>
<section id="fishers-exact-test" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="fishers-exact-test"><span class="header-section-number">20.2</span> Fisher’s Exact Test</h2>
<p><strong>Fisher’s exact test</strong> evaluates association between categorical variables by calculating exact probabilities rather than relying on the chi-square approximation.</p>
<p>It is especially useful when sample sizes are small.</p>
<p>The test considers all possible tables with the same row and column totals and asks:</p>
<blockquote class="blockquote">
<p>How many of those possible tables are as extreme as, or more extreme than, the observed table?</p>
</blockquote>
<p>The result is an exact p-value.</p>
<p>Fisher’s exact test can be used for 2-by-2 tables and, in some software, for larger tables. However, for large tables with many categories, the computation may become memory intensive.</p>
<hr>
</section>
<section id="fishers-exact-test-in-software" class="level2" data-number="20.3">
<h2 data-number="20.3" class="anchored" data-anchor-id="fishers-exact-test-in-software"><span class="header-section-number">20.3</span> Fisher’s Exact Test in Software</h2>
<p>In Stata:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">tab</span> yvar xvar, exact</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>or:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">tab</span> yvar xvar, col chi exact</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>In R:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>mytable <span class="ot">&lt;-</span> <span class="fu">table</span>(yvar, xvar)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(mytable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Fisher’s exact test reports a p-value directly.</p>
<p>If expected cell counts are too small for chi-square, Fisher’s exact test is the safer option.</p>
<hr>
</section>
</section>
<section id="part-ix-limitations-of-the-chi-square-test" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> Part IX: Limitations of the Chi-Square Test</h1>
<section id="direction" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="direction"><span class="header-section-number">21.1</span> Direction</h2>
<p>The chi-square statistic does not tell us the direction of the relationship.</p>
<p>It tells us whether variables are independent, not how they are related.</p>
<p>To understand direction, examine:</p>
<ul>
<li>column percentages</li>
<li>row percentages</li>
<li>residuals</li>
<li>standardized residuals</li>
<li>ordinal association measures, if appropriate</li>
</ul>
<hr>
</section>
<section id="magnitude" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="magnitude"><span class="header-section-number">21.2</span> Magnitude</h2>
<p>The chi-square statistic does not directly tell us the substantive magnitude of the relationship.</p>
<p>With a large enough sample, even small differences can become statistically significant.</p>
<p>For example, a difference between 51 percent and 53 percent may be statistically significant in a huge sample, but substantively small.</p>
<p>Always distinguish statistical significance from substantive significance.</p>
<hr>
</section>
<section id="category-choices" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="category-choices"><span class="header-section-number">21.3</span> Category Choices</h2>
<p>Chi-square results can depend on how categories are defined.</p>
<p>If researchers combine or split categories differently, the table changes, and the chi-square result may change.</p>
<p>For example, a political scientist might classify regimes as:</p>
<ul>
<li>democracy</li>
<li>non-democracy</li>
</ul>
<p>or instead as:</p>
<ul>
<li>non-democracy</li>
<li>presidential democracy</li>
<li>parliamentary democracy</li>
</ul>
<p>The chi-square statistic may differ across these choices.</p>
<p>Researchers should be transparent about categorization decisions and check whether results are sensitive to alternative classifications.</p>
<hr>
</section>
</section>
<section id="key-terms" class="level1" data-number="22">
<h1 data-number="22"><span class="header-section-number">22</span> Key Terms</h1>
<p><strong>Categorical variable</strong><br>
A variable whose values are categories.</p>
<p><strong>Cross-tabulation</strong><br>
A table showing the joint distribution of two categorical variables.</p>
<p><strong>Contingency table</strong><br>
Another term for a cross-tabulation.</p>
<p><strong>Observed frequency</strong><br>
The actual number of cases observed in a cell.</p>
<p><strong>Expected frequency</strong><br>
The number of cases expected in a cell under the null hypothesis of independence.</p>
<p><strong>Chi-square test of independence</strong><br>
A test of whether two categorical variables are independent.</p>
<p><strong>Chi-square statistic</strong><br>
A statistic measuring the discrepancy between observed and expected frequencies.</p>
<p><strong>Chi-square distribution</strong><br>
A right-skewed distribution used for chi-square tests.</p>
<p><strong>Residual</strong><br>
The difference between observed and expected frequency in a cell.</p>
<p><strong>Standardized residual</strong><br>
A residual converted into standard error units.</p>
<p><strong>Degrees of freedom</strong><br>
For a chi-square test, <span class="math inline">\((r-1)(c-1)\)</span>, where <span class="math inline">\(r\)</span> is rows and <span class="math inline">\(c\)</span> is columns.</p>
<p><strong>Fisher’s exact test</strong><br>
An exact test for association between categorical variables, useful for small samples.</p>
<p><strong>Ordinal association</strong><br>
Association between variables whose categories have a meaningful order.</p>
<p><strong>Gamma</strong><br>
A statistic measuring the direction and strength of association between ordinal variables.</p>
<p><strong>Kendall’s tau-b</strong><br>
Another statistic measuring ordinal association.</p>
<p><strong>Statistical significance</strong><br>
Evidence that an observed pattern is unlikely under the null hypothesis.</p>
<p><strong>Substantive significance</strong><br>
The practical or real-world importance of an observed pattern.</p>
<hr>
</section>
<section id="chapter-summary" class="level1" data-number="23">
<h1 data-number="23"><span class="header-section-number">23</span> Chapter Summary</h1>
<p>The chi-square test of independence allows us to evaluate whether two categorical variables are statistically independent.</p>
<p>The test compares observed frequencies in a contingency table to expected frequencies under the null hypothesis of independence. If the observed frequencies deviate enough from the expected frequencies, the chi-square statistic becomes large, and we reject the null hypothesis.</p>
<p>Expected frequencies are calculated using row totals, column totals, and the total sample size:</p>
<p><span class="math display">\[
f_e = \frac{(\text{row total})(\text{column total})}{n}
\]</span></p>
<p>The chi-square statistic is:</p>
<p><span class="math display">\[
\chi^2 =
\sum
\frac{(f_o-f_e)^2}{f_e}
\]</span></p>
<p>The test is one-sided because chi-square statistics cannot be negative. The critical value depends on the chi-square distribution and degrees of freedom:</p>
<p><span class="math display">\[
df = (r-1)(c-1)
\]</span></p>
<p>A significant chi-square test tells us the variables are not independent. It does not tell us the direction or substantive magnitude of the relationship. To understand those, we examine percentages, residuals, standardized residuals, and, for ordinal variables, statistics such as gamma or Kendall’s tau-b.</p>
<p>For small samples, when expected frequencies are too low, Fisher’s exact test is preferable.</p>
<p>The central lesson is that categorical relationships require careful interpretation. Statistical significance tells us that a pattern is unlikely under independence, but substantive interpretation comes from examining the table itself.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter-10.html" class="pagination-link" aria-label="Chapter 10: Comparison of Two Groups">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter-12.html" class="pagination-link" aria-label="Chapter 12: ANOVA">
        <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>