<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>11&nbsp; Chapter 10: Comparison of Two Groups – PubPol 529: Coursebook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter-11.html" rel="next">
<link href="./chapter-9.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e944e0e12dd6c2e1651c888e836d9b4b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter-10.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PubPol 529: Coursebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">PubPol 529: Coursebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 1: Measurement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 2: Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 3: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 5: Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 6: Sampling Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 7: Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 8: Significance Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 9: Experiments and Causality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-10.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 13: Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chapter 14: Linear Regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#part-i-mean-comparison-tables" id="toc-part-i-mean-comparison-tables" class="nav-link active" data-scroll-target="#part-i-mean-comparison-tables"><span class="header-section-number">12</span> Part I: Mean Comparison Tables</a>
  <ul class="collapse">
  <li><a href="#what-is-a-mean-comparison-table" id="toc-what-is-a-mean-comparison-table" class="nav-link" data-scroll-target="#what-is-a-mean-comparison-table"><span class="header-section-number">12.1</span> What Is a Mean Comparison Table?</a></li>
  <li><a href="#general-structure" id="toc-general-structure" class="nav-link" data-scroll-target="#general-structure"><span class="header-section-number">12.2</span> General Structure</a></li>
  <li><a href="#example-racial-representation-and-arrest-disparities" id="toc-example-racial-representation-and-arrest-disparities" class="nav-link" data-scroll-target="#example-racial-representation-and-arrest-disparities"><span class="header-section-number">12.3</span> Example: Racial Representation and Arrest Disparities</a></li>
  <li><a href="#measuring-arrest-disparities" id="toc-measuring-arrest-disparities" class="nav-link" data-scroll-target="#measuring-arrest-disparities"><span class="header-section-number">12.4</span> Measuring Arrest Disparities</a></li>
  <li><a href="#mean-comparison-table-city-council-composition" id="toc-mean-comparison-table-city-council-composition" class="nav-link" data-scroll-target="#mean-comparison-table-city-council-composition"><span class="header-section-number">12.5</span> Mean Comparison Table: City Council Composition</a></li>
  </ul></li>
  <li><a href="#part-ii-difference-of-means-tests" id="toc-part-ii-difference-of-means-tests" class="nav-link" data-scroll-target="#part-ii-difference-of-means-tests"><span class="header-section-number">13</span> Part II: Difference-of-Means Tests</a>
  <ul class="collapse">
  <li><a href="#the-difference-of-means-as-a-statistic" id="toc-the-difference-of-means-as-a-statistic" class="nav-link" data-scroll-target="#the-difference-of-means-as-a-statistic"><span class="header-section-number">13.1</span> The Difference of Means as a Statistic</a></li>
  <li><a href="#why-the-standard-error-changes" id="toc-why-the-standard-error-changes" class="nav-link" data-scroll-target="#why-the-standard-error-changes"><span class="header-section-number">13.2</span> Why the Standard Error Changes</a></li>
  <li><a href="#independent-and-dependent-samples" id="toc-independent-and-dependent-samples" class="nav-link" data-scroll-target="#independent-and-dependent-samples"><span class="header-section-number">13.3</span> Independent and Dependent Samples</a>
  <ul class="collapse">
  <li><a href="#independent-samples" id="toc-independent-samples" class="nav-link" data-scroll-target="#independent-samples"><span class="header-section-number">13.3.1</span> Independent Samples</a></li>
  <li><a href="#dependent-samples" id="toc-dependent-samples" class="nav-link" data-scroll-target="#dependent-samples"><span class="header-section-number">13.3.2</span> Dependent Samples</a></li>
  </ul></li>
  <li><a href="#standard-error-for-the-difference-of-means-independent-samples" id="toc-standard-error-for-the-difference-of-means-independent-samples" class="nav-link" data-scroll-target="#standard-error-for-the-difference-of-means-independent-samples"><span class="header-section-number">13.4</span> Standard Error for the Difference of Means: Independent Samples</a></li>
  <li><a href="#confidence-interval-for-a-difference-of-means" id="toc-confidence-interval-for-a-difference-of-means" class="nav-link" data-scroll-target="#confidence-interval-for-a-difference-of-means"><span class="header-section-number">13.5</span> Confidence Interval for a Difference of Means</a></li>
  <li><a href="#degrees-of-freedom-for-independent-sample-mean-tests" id="toc-degrees-of-freedom-for-independent-sample-mean-tests" class="nav-link" data-scroll-target="#degrees-of-freedom-for-independent-sample-mean-tests"><span class="header-section-number">13.6</span> Degrees of Freedom for Independent-Sample Mean Tests</a></li>
  <li><a href="#example-city-councils-and-arrest-disparities" id="toc-example-city-councils-and-arrest-disparities" class="nav-link" data-scroll-target="#example-city-councils-and-arrest-disparities"><span class="header-section-number">13.7</span> Example: City Councils and Arrest Disparities</a></li>
  <li><a href="#confidence-interval-for-the-difference" id="toc-confidence-interval-for-the-difference" class="nav-link" data-scroll-target="#confidence-interval-for-the-difference"><span class="header-section-number">13.8</span> Confidence Interval for the Difference</a></li>
  <li><a href="#significance-test-for-the-difference-of-means" id="toc-significance-test-for-the-difference-of-means" class="nav-link" data-scroll-target="#significance-test-for-the-difference-of-means"><span class="header-section-number">13.9</span> Significance Test for the Difference of Means</a></li>
  <li><a href="#statistical-significance-is-not-causality" id="toc-statistical-significance-is-not-causality" class="nav-link" data-scroll-target="#statistical-significance-is-not-causality"><span class="header-section-number">13.10</span> Statistical Significance Is Not Causality</a></li>
  </ul></li>
  <li><a href="#part-iii-another-difference-of-means-example" id="toc-part-iii-another-difference-of-means-example" class="nav-link" data-scroll-target="#part-iii-another-difference-of-means-example"><span class="header-section-number">14</span> Part III: Another Difference-of-Means Example</a>
  <ul class="collapse">
  <li><a href="#democracies-and-infant-mortality" id="toc-democracies-and-infant-mortality" class="nav-link" data-scroll-target="#democracies-and-infant-mortality"><span class="header-section-number">14.1</span> Democracies and Infant Mortality</a></li>
  <li><a href="#checking-assumptions" id="toc-checking-assumptions" class="nav-link" data-scroll-target="#checking-assumptions"><span class="header-section-number">14.2</span> Checking Assumptions</a></li>
  <li><a href="#standard-error-for-the-difference" id="toc-standard-error-for-the-difference" class="nav-link" data-scroll-target="#standard-error-for-the-difference"><span class="header-section-number">14.3</span> Standard Error for the Difference</a></li>
  <li><a href="#confidence-interval" id="toc-confidence-interval" class="nav-link" data-scroll-target="#confidence-interval"><span class="header-section-number">14.4</span> Confidence Interval</a></li>
  <li><a href="#significance-test" id="toc-significance-test" class="nav-link" data-scroll-target="#significance-test"><span class="header-section-number">14.5</span> Significance Test</a></li>
  </ul></li>
  <li><a href="#part-iv-difference-of-proportions-tests" id="toc-part-iv-difference-of-proportions-tests" class="nav-link" data-scroll-target="#part-iv-difference-of-proportions-tests"><span class="header-section-number">15</span> Part IV: Difference-of-Proportions Tests</a>
  <ul class="collapse">
  <li><a href="#comparing-two-proportions" id="toc-comparing-two-proportions" class="nav-link" data-scroll-target="#comparing-two-proportions"><span class="header-section-number">15.1</span> Comparing Two Proportions</a></li>
  <li><a href="#sample-size-rule-for-difference-of-proportions" id="toc-sample-size-rule-for-difference-of-proportions" class="nav-link" data-scroll-target="#sample-size-rule-for-difference-of-proportions"><span class="header-section-number">15.2</span> Sample Size Rule for Difference of Proportions</a></li>
  <li><a href="#example-graduation-program" id="toc-example-graduation-program" class="nav-link" data-scroll-target="#example-graduation-program"><span class="header-section-number">15.3</span> Example: Graduation Program</a></li>
  <li><a href="#confidence-interval-for-a-difference-of-proportions" id="toc-confidence-interval-for-a-difference-of-proportions" class="nav-link" data-scroll-target="#confidence-interval-for-a-difference-of-proportions"><span class="header-section-number">15.4</span> Confidence Interval for a Difference of Proportions</a></li>
  <li><a href="#why-can-the-confidence-interval-include-negative-values" id="toc-why-can-the-confidence-interval-include-negative-values" class="nav-link" data-scroll-target="#why-can-the-confidence-interval-include-negative-values"><span class="header-section-number">15.5</span> Why Can the Confidence Interval Include Negative Values?</a></li>
  <li><a href="#significance-test-for-difference-of-proportions" id="toc-significance-test-for-difference-of-proportions" class="nav-link" data-scroll-target="#significance-test-for-difference-of-proportions"><span class="header-section-number">15.6</span> Significance Test for Difference of Proportions</a></li>
  <li><a href="#z-test-for-difference-of-proportions" id="toc-z-test-for-difference-of-proportions" class="nav-link" data-scroll-target="#z-test-for-difference-of-proportions"><span class="header-section-number">15.7</span> z-Test for Difference of Proportions</a></li>
  </ul></li>
  <li><a href="#part-v-dependent-samples" id="toc-part-v-dependent-samples" class="nav-link" data-scroll-target="#part-v-dependent-samples"><span class="header-section-number">16</span> Part V: Dependent Samples</a>
  <ul class="collapse">
  <li><a href="#what-are-dependent-samples" id="toc-what-are-dependent-samples" class="nav-link" data-scroll-target="#what-are-dependent-samples"><span class="header-section-number">16.1</span> What Are Dependent Samples?</a></li>
  <li><a href="#turning-a-two-sample-problem-into-a-one-sample-problem" id="toc-turning-a-two-sample-problem-into-a-one-sample-problem" class="nav-link" data-scroll-target="#turning-a-two-sample-problem-into-a-one-sample-problem"><span class="header-section-number">16.2</span> Turning a Two-Sample Problem into a One-Sample Problem</a></li>
  <li><a href="#example-matched-pairs" id="toc-example-matched-pairs" class="nav-link" data-scroll-target="#example-matched-pairs"><span class="header-section-number">16.3</span> Example: Matched Pairs</a></li>
  <li><a href="#standard-error-for-dependent-samples" id="toc-standard-error-for-dependent-samples" class="nav-link" data-scroll-target="#standard-error-for-dependent-samples"><span class="header-section-number">16.4</span> Standard Error for Dependent Samples</a></li>
  <li><a href="#example-lead-pipe-replacement" id="toc-example-lead-pipe-replacement" class="nav-link" data-scroll-target="#example-lead-pipe-replacement"><span class="header-section-number">16.5</span> Example: Lead Pipe Replacement</a></li>
  </ul></li>
  <li><a href="#part-vi-equal-variance-assumption" id="toc-part-vi-equal-variance-assumption" class="nav-link" data-scroll-target="#part-vi-equal-variance-assumption"><span class="header-section-number">17</span> Part VI: Equal Variance Assumption</a>
  <ul class="collapse">
  <li><a href="#what-is-the-equal-variance-assumption" id="toc-what-is-the-equal-variance-assumption" class="nav-link" data-scroll-target="#what-is-the-equal-variance-assumption"><span class="header-section-number">17.1</span> What Is the Equal Variance Assumption?</a></li>
  <li><a href="#when-might-equal-variances-be-plausible" id="toc-when-might-equal-variances-be-plausible" class="nav-link" data-scroll-target="#when-might-equal-variances-be-plausible"><span class="header-section-number">17.2</span> When Might Equal Variances Be Plausible?</a></li>
  <li><a href="#why-the-assumption-matters" id="toc-why-the-assumption-matters" class="nav-link" data-scroll-target="#why-the-assumption-matters"><span class="header-section-number">17.3</span> Why the Assumption Matters</a></li>
  <li><a href="#pooled-standard-deviation" id="toc-pooled-standard-deviation" class="nav-link" data-scroll-target="#pooled-standard-deviation"><span class="header-section-number">17.4</span> Pooled Standard Deviation</a></li>
  <li><a href="#standard-error-with-equal-variances" id="toc-standard-error-with-equal-variances" class="nav-link" data-scroll-target="#standard-error-with-equal-variances"><span class="header-section-number">17.5</span> Standard Error with Equal Variances</a></li>
  <li><a href="#example-temperatures-in-ann-arbor" id="toc-example-temperatures-in-ann-arbor" class="nav-link" data-scroll-target="#example-temperatures-in-ann-arbor"><span class="header-section-number">17.6</span> Example: Temperatures in Ann Arbor</a></li>
  <li><a href="#pooled-standard-deviation-calculation" id="toc-pooled-standard-deviation-calculation" class="nav-link" data-scroll-target="#pooled-standard-deviation-calculation"><span class="header-section-number">17.7</span> Pooled Standard Deviation Calculation</a></li>
  </ul></li>
  <li><a href="#part-vii-small-sample-alternatives" id="toc-part-vii-small-sample-alternatives" class="nav-link" data-scroll-target="#part-vii-small-sample-alternatives"><span class="header-section-number">18</span> Part VII: Small-Sample Alternatives</a>
  <ul class="collapse">
  <li><a href="#when-the-usual-tests-do-not-work" id="toc-when-the-usual-tests-do-not-work" class="nav-link" data-scroll-target="#when-the-usual-tests-do-not-work"><span class="header-section-number">18.1</span> When the Usual Tests Do Not Work</a></li>
  <li><a href="#fishers-exact-test-for-small-sample-proportions" id="toc-fishers-exact-test-for-small-sample-proportions" class="nav-link" data-scroll-target="#fishers-exact-test-for-small-sample-proportions"><span class="header-section-number">18.2</span> Fisher’s Exact Test for Small-Sample Proportions</a></li>
  <li><a href="#example-sleep-and-masters-students" id="toc-example-sleep-and-masters-students" class="nav-link" data-scroll-target="#example-sleep-and-masters-students"><span class="header-section-number">18.3</span> Example: Sleep and Master’s Students</a></li>
  <li><a href="#wilcoxon-mann-whitney-test-for-small-sample-independent-means" id="toc-wilcoxon-mann-whitney-test-for-small-sample-independent-means" class="nav-link" data-scroll-target="#wilcoxon-mann-whitney-test-for-small-sample-independent-means"><span class="header-section-number">18.4</span> Wilcoxon-Mann-Whitney Test for Small-Sample Independent Means</a></li>
  <li><a href="#example-democracy-and-gdp-per-capita" id="toc-example-democracy-and-gdp-per-capita" class="nav-link" data-scroll-target="#example-democracy-and-gdp-per-capita"><span class="header-section-number">18.5</span> Example: Democracy and GDP per Capita</a></li>
  <li><a href="#wilcoxon-signed-rank-test-for-dependent-samples" id="toc-wilcoxon-signed-rank-test-for-dependent-samples" class="nav-link" data-scroll-target="#wilcoxon-signed-rank-test-for-dependent-samples"><span class="header-section-number">18.6</span> Wilcoxon Signed-Rank Test for Dependent Samples</a></li>
  </ul></li>
  <li><a href="#part-viii-controlled-comparisons-of-means" id="toc-part-viii-controlled-comparisons-of-means" class="nav-link" data-scroll-target="#part-viii-controlled-comparisons-of-means"><span class="header-section-number">19</span> Part VIII: Controlled Comparisons of Means</a>
  <ul class="collapse">
  <li><a href="#why-add-a-control-variable" id="toc-why-add-a-control-variable" class="nav-link" data-scroll-target="#why-add-a-control-variable"><span class="header-section-number">19.1</span> Why Add a Control Variable?</a></li>
  <li><a href="#controlling-in-a-mean-comparison-table" id="toc-controlling-in-a-mean-comparison-table" class="nav-link" data-scroll-target="#controlling-in-a-mean-comparison-table"><span class="header-section-number">19.2</span> Controlling in a Mean Comparison Table</a></li>
  <li><a href="#example-democracy-wealth-and-life-expectancy" id="toc-example-democracy-wealth-and-life-expectancy" class="nav-link" data-scroll-target="#example-democracy-wealth-and-life-expectancy"><span class="header-section-number">19.3</span> Example: Democracy, Wealth, and Life Expectancy</a></li>
  <li><a href="#additive-relationships" id="toc-additive-relationships" class="nav-link" data-scroll-target="#additive-relationships"><span class="header-section-number">19.4</span> Additive Relationships</a></li>
  <li><a href="#spurious-relationships" id="toc-spurious-relationships" class="nav-link" data-scroll-target="#spurious-relationships"><span class="header-section-number">19.5</span> Spurious Relationships</a></li>
  <li><a href="#interactive-relationships" id="toc-interactive-relationships" class="nav-link" data-scroll-target="#interactive-relationships"><span class="header-section-number">19.6</span> Interactive Relationships</a></li>
  <li><a href="#limits-of-controlled-mean-tables" id="toc-limits-of-controlled-mean-tables" class="nav-link" data-scroll-target="#limits-of-controlled-mean-tables"><span class="header-section-number">19.7</span> Limits of Controlled Mean Tables</a></li>
  </ul></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">20</span> Key Terms</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">21</span> Chapter Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We now move from one-sample inference to <strong>two-sample inference</strong>.</p>
<p>In earlier chapters, we learned how to estimate and test claims about a single population mean or a single population proportion. We used sample statistics to estimate population parameters, calculated standard errors, constructed confidence intervals, and conducted significance tests.</p>
<p>Now we extend those same ideas to comparisons between groups.</p>
<p>Many policy and social science questions are comparative:</p>
<ul>
<li>Do students whose teachers have master’s degrees score higher on tests?</li>
<li>Do democracies have lower infant mortality than non-democracies?</li>
<li>Are graduation rates higher among students who participate in a program?</li>
<li>Do cities with more racially diverse city councils have lower racial disparities in arrests?</li>
<li>Does a policy intervention reduce lead levels, air pollution, or absenteeism?</li>
</ul>
<p>These questions require comparing means or proportions across two or more groups.</p>
<p>The logic is familiar: estimate something, calculate uncertainty around the estimate, and test whether the observed difference is large enough to reject a null hypothesis. What changes is that we are no longer estimating one statistic. We are estimating a <strong>difference</strong> between two statistics.</p>
<p>A difference is itself a statistic. Therefore, it has a standard error.</p>
<p>This chapter introduces mean comparison tables, difference-of-means tests, difference-of-proportions tests, dependent samples, equal variance assumptions, small-sample alternatives, and controlled comparisons of means.</p>
<hr>
<section id="part-i-mean-comparison-tables" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> Part I: Mean Comparison Tables</h1>
<section id="what-is-a-mean-comparison-table" class="level2" data-number="12.1">
<h2 data-number="12.1" class="anchored" data-anchor-id="what-is-a-mean-comparison-table"><span class="header-section-number">12.1</span> What Is a Mean Comparison Table?</h2>
<p>A <strong>mean comparison table</strong> displays the mean of an interval-level variable across categories of another variable.</p>
<p>The variable whose mean we calculate is usually the outcome variable, or dependent variable. It must be measured at the interval or ratio level.</p>
<p>The variable that creates the groups is categorical. It may be nominal or ordinal.</p>
<p>For example, suppose we want to know whether students whose teachers have master’s degrees score higher on standardized tests than students whose teachers do not have master’s degrees.</p>
<p>The outcome variable is:</p>
<ul>
<li>student test score</li>
</ul>
<p>The grouping variable is:</p>
<ul>
<li>teacher has a master’s degree</li>
<li>teacher does not have a master’s degree</li>
</ul>
<p>A mean comparison table would show the mean test score in each group.</p>
<hr>
</section>
<section id="general-structure" class="level2" data-number="12.2">
<h2 data-number="12.2" class="anchored" data-anchor-id="general-structure"><span class="header-section-number">12.2</span> General Structure</h2>
<p>A simple mean comparison table might look like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category of <span class="math inline">\(X\)</span></th>
<th style="text-align: right;">Mean of <span class="math inline">\(Y\)</span></th>
<th style="text-align: right;">Number of Cases</th>
<th style="text-align: right;">Percent of Sample</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Category 1</td>
<td style="text-align: right;"><span class="math inline">\(\bar{Y}_1\)</span></td>
<td style="text-align: right;"><span class="math inline">\(n_1\)</span></td>
<td style="text-align: right;">%</td>
</tr>
<tr class="even">
<td>Category 2</td>
<td style="text-align: right;"><span class="math inline">\(\bar{Y}_2\)</span></td>
<td style="text-align: right;"><span class="math inline">\(n_2\)</span></td>
<td style="text-align: right;">%</td>
</tr>
<tr class="odd">
<td>Category 3</td>
<td style="text-align: right;"><span class="math inline">\(\bar{Y}_3\)</span></td>
<td style="text-align: right;"><span class="math inline">\(n_3\)</span></td>
<td style="text-align: right;">%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><span class="math inline">\(\bar{Y}\)</span></td>
<td style="text-align: right;"><span class="math inline">\(n\)</span></td>
<td style="text-align: right;">100%</td>
</tr>
</tbody>
</table>
<p>The full sample is divided into subsamples based on the categories of <span class="math inline">\(X\)</span>. Within each subsample, we calculate the mean of <span class="math inline">\(Y\)</span>.</p>
<p>The table provides a descriptive comparison. It tells us whether the sample means differ across groups.</p>
<p>However, the table alone does not tell us whether those differences are statistically significant.</p>
<p>For that, we need a significance test.</p>
<hr>
</section>
<section id="example-racial-representation-and-arrest-disparities" class="level2" data-number="12.3">
<h2 data-number="12.3" class="anchored" data-anchor-id="example-racial-representation-and-arrest-disparities"><span class="header-section-number">12.3</span> Example: Racial Representation and Arrest Disparities</h2>
<p>Consider a study by political scientist Laurel Eckhouse on racial disparities in arrests for minor offenses.</p>
<p>The research question is whether racial representation on city councils is associated with racial disparities in policing.</p>
<p>In the United States, policing is largely local. City governments often have authority over police departments, budgets, oversight, and local ordinances. Therefore, the racial composition of a city council may plausibly affect policing practices.</p>
<p>The independent variable is city council composition:</p>
<ul>
<li>majority white city council</li>
<li>majority persons of color city council</li>
</ul>
<p>The dependent variable is a measure of racial disparity in arrests.</p>
<p>Eckhouse focuses on arrests for minor offenses, where police officers often have discretion. Examples might include loitering, being in a park after hours, disorderly conduct, or other low-level offenses. Discretion is important because disparities may be more likely to appear when officers have more room to decide whether to arrest, warn, or ignore.</p>
<hr>
</section>
<section id="measuring-arrest-disparities" class="level2" data-number="12.4">
<h2 data-number="12.4" class="anchored" data-anchor-id="measuring-arrest-disparities"><span class="header-section-number">12.4</span> Measuring Arrest Disparities</h2>
<p>A simple count of arrests would not be sufficient because cities differ in population size.</p>
<p>Instead, Eckhouse uses an <strong>arrest rate ratio</strong>:</p>
<p><span class="math display">\[
\text{Arrest Rate Ratio}
=
\frac{\text{Black arrests per Black resident}}
{\text{White arrests per White resident}}
\]</span></p>
<p>This ratio compares the arrest rate for Black residents to the arrest rate for white residents.</p>
<p>Interpretation:</p>
<ul>
<li>A value of 1 means equal arrest rates.</li>
<li>A value of 2 means the arrest rate for Black residents is twice the arrest rate for white residents.</li>
<li>A value above 1 indicates higher arrest rates for Black residents.</li>
<li>A value below 1 would indicate lower arrest rates for Black residents.</li>
</ul>
<p>This measure allows comparison across cities of different sizes.</p>
<hr>
</section>
<section id="mean-comparison-table-city-council-composition" class="level2" data-number="12.5">
<h2 data-number="12.5" class="anchored" data-anchor-id="mean-comparison-table-city-council-composition"><span class="header-section-number">12.5</span> Mean Comparison Table: City Council Composition</h2>
<p>The mean comparison table from the study is approximately:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>City Council Composition</th>
<th style="text-align: right;">Mean Arrest Rate Ratio</th>
<th style="text-align: right;">Number of Cities</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Majority white city council</td>
<td style="text-align: right;">2.63</td>
<td style="text-align: right;">1,094</td>
</tr>
<tr class="even">
<td>Majority persons of color city council</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">94</td>
</tr>
<tr class="odd">
<td><strong>Overall</strong></td>
<td style="text-align: right;">2.57</td>
<td style="text-align: right;">1,188</td>
</tr>
</tbody>
</table>
<p>The mean arrest rate ratio is 2.63 in cities with majority white city councils. That means Black residents are arrested for minor offenses at about 2.6 times the rate of white residents.</p>
<p>In cities with majority persons of color city councils, the mean arrest rate ratio is 1.88.</p>
<p>The observed difference is:</p>
<p><span class="math display">\[
2.63 - 1.88 = 0.75
\]</span></p>
<p>This descriptive table suggests that racial disparities in arrests are lower in cities with majority persons of color city councils.</p>
<p>But is that difference statistically significant?</p>
<p>And even if it is statistically significant, is it causal?</p>
<p>Those are separate questions.</p>
<hr>
</section>
</section>
<section id="part-ii-difference-of-means-tests" class="level1" data-number="13">
<h1 data-number="13"><span class="header-section-number">13</span> Part II: Difference-of-Means Tests</h1>
<section id="the-difference-of-means-as-a-statistic" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="the-difference-of-means-as-a-statistic"><span class="header-section-number">13.1</span> The Difference of Means as a Statistic</h2>
<p>When we compare two means, we estimate a new statistic:</p>
<p><span class="math display">\[
\bar{Y}_2 - \bar{Y}_1
\]</span></p>
<p>This statistic estimates the difference between two population means:</p>
<p><span class="math display">\[
\mu_2 - \mu_1
\]</span></p>
<p>The null hypothesis is usually that there is no difference:</p>
<p><span class="math display">\[
H_0: \mu_2 - \mu_1 = 0
\]</span></p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[
H_A: \mu_2 - \mu_1 \neq 0
\]</span></p>
<p>If the observed difference is large relative to its standard error, we reject the null hypothesis.</p>
<hr>
</section>
<section id="why-the-standard-error-changes" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="why-the-standard-error-changes"><span class="header-section-number">13.2</span> Why the Standard Error Changes</h2>
<p>When we tested one mean, we compared a sample mean to a fixed null-hypothesized value.</p>
<p>Now we compare two sample means. Both are estimated with uncertainty.</p>
<p>Each sample mean has its own standard error:</p>
<p><span class="math display">\[
SE_{\bar{Y}_1}
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
SE_{\bar{Y}_2}
\]</span></p>
<p>Because both means are uncertain, the difference between them is also uncertain.</p>
<p>The standard error for the difference must incorporate uncertainty from both samples.</p>
<hr>
</section>
<section id="independent-and-dependent-samples" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="independent-and-dependent-samples"><span class="header-section-number">13.3</span> Independent and Dependent Samples</h2>
<p>Before calculating the standard error, we must determine whether the samples are <strong>independent</strong> or <strong>dependent</strong>.</p>
<section id="independent-samples" class="level3" data-number="13.3.1">
<h3 data-number="13.3.1" class="anchored" data-anchor-id="independent-samples"><span class="header-section-number">13.3.1</span> Independent Samples</h3>
<p>Samples are independent when the observations in one group are not explicitly matched with observations in the other group.</p>
<p>Examples:</p>
<ul>
<li>Democrats versus Republicans</li>
<li>treatment group versus control group in a randomized experiment</li>
<li>cities with majority white city councils versus cities with majority persons of color city councils</li>
<li>democracies versus non-democracies</li>
<li>students in one program versus students not in the program</li>
</ul>
<p>Independent samples are the default in most two-sample tests.</p>
</section>
<section id="dependent-samples" class="level3" data-number="13.3.2">
<h3 data-number="13.3.2" class="anchored" data-anchor-id="dependent-samples"><span class="header-section-number">13.3.2</span> Dependent Samples</h3>
<p>Samples are dependent when observations are explicitly paired.</p>
<p>Examples:</p>
<ul>
<li>the same people measured before and after an intervention</li>
<li>twins split between treatment and control</li>
<li>matched pairs of similar cases</li>
<li>households measured before and after lead pipe replacement</li>
</ul>
<p>Dependent samples require a different test because the observations are connected.</p>
<hr>
</section>
</section>
<section id="standard-error-for-the-difference-of-means-independent-samples" class="level2" data-number="13.4">
<h2 data-number="13.4" class="anchored" data-anchor-id="standard-error-for-the-difference-of-means-independent-samples"><span class="header-section-number">13.4</span> Standard Error for the Difference of Means: Independent Samples</h2>
<p>For independent samples, the standard error of the difference between two means is:</p>
<p><span class="math display">\[
SE_{\bar{Y}_2-\bar{Y}_1}
=
\sqrt{SE_{\bar{Y}_1}^2 + SE_{\bar{Y}_2}^2}
\]</span></p>
<p>For a single mean:</p>
<p><span class="math display">\[
SE_{\bar{Y}} = \frac{s}{\sqrt{n}}
\]</span></p>
<p>So for two independent means:</p>
<p><span class="math display">\[
SE_{\bar{Y}_2-\bar{Y}_1}
=
\sqrt{
\frac{s_1^2}{n_1}
+
\frac{s_2^2}{n_2}
}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(s_1\)</span> is the standard deviation in sample 1</li>
<li><span class="math inline">\(s_2\)</span> is the standard deviation in sample 2</li>
<li><span class="math inline">\(n_1\)</span> is the size of sample 1</li>
<li><span class="math inline">\(n_2\)</span> is the size of sample 2</li>
</ul>
<p>This formula takes the variance of each sample mean, adds them together, and then takes the square root.</p>
<p>The structure resembles the Pythagorean theorem: square, add, square root. Statistics has a few geometry flashbacks. It happens.</p>
<hr>
</section>
<section id="confidence-interval-for-a-difference-of-means" class="level2" data-number="13.5">
<h2 data-number="13.5" class="anchored" data-anchor-id="confidence-interval-for-a-difference-of-means"><span class="header-section-number">13.5</span> Confidence Interval for a Difference of Means</h2>
<p>The confidence interval for a difference of means is:</p>
<p><span class="math display">\[
(\bar{Y}_2 - \bar{Y}_1)
\pm
t^* SE_{\bar{Y}_2-\bar{Y}_1}
\]</span></p>
<p>or:</p>
<p><span class="math display">\[
(\bar{Y}_2 - \bar{Y}_1)
\pm
t^*
\sqrt{
\frac{s_1^2}{n_1}
+
\frac{s_2^2}{n_2}
}
\]</span></p>
<p>The point estimate is the observed difference between sample means.</p>
<p>The margin of error is:</p>
<p><span class="math display">\[
t^* SE_{\bar{Y}_2-\bar{Y}_1}
\]</span></p>
<p>The t critical value depends on degrees of freedom.</p>
<hr>
</section>
<section id="degrees-of-freedom-for-independent-sample-mean-tests" class="level2" data-number="13.6">
<h2 data-number="13.6" class="anchored" data-anchor-id="degrees-of-freedom-for-independent-sample-mean-tests"><span class="header-section-number">13.6</span> Degrees of Freedom for Independent-Sample Mean Tests</h2>
<p>Degrees of freedom are more complicated for two independent means than for one mean.</p>
<p>For one mean:</p>
<p><span class="math display">\[
df = n - 1
\]</span></p>
<p>For two independent means without assuming equal variances, the exact degrees of freedom are given by the Satterthwaite approximation, which is complicated:</p>
<p><span class="math display">\[
df =
\frac{
\left(\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}\right)^2
}
{
\frac{\left(\frac{s_1^2}{n_1}\right)^2}{n_1-1}
+
\frac{\left(\frac{s_2^2}{n_2}\right)^2}{n_2-1}
}
\]</span></p>
<p>Software uses this formula.</p>
<p>By hand, we often use a conservative approximation:</p>
<p><span class="math display">\[
df = \min(n_1-1, n_2-1)
\]</span></p>
<p>That is, take the smaller sample size and subtract 1.</p>
<p>This underestimates the true degrees of freedom, making the test slightly more conservative. If we can reject the null hypothesis using this conservative approximation, we would also reject using the more exact degrees of freedom.</p>
<hr>
</section>
<section id="example-city-councils-and-arrest-disparities" class="level2" data-number="13.7">
<h2 data-number="13.7" class="anchored" data-anchor-id="example-city-councils-and-arrest-disparities"><span class="header-section-number">13.7</span> Example: City Councils and Arrest Disparities</h2>
<p>Return to the arrest disparity example.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>City Council Composition</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Sample Size</th>
<th style="text-align: right;">Standard Error</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Majority white</td>
<td style="text-align: right;">2.63</td>
<td style="text-align: right;">2.401</td>
<td style="text-align: right;">1,094</td>
<td style="text-align: right;">0.073</td>
</tr>
<tr class="even">
<td>Majority persons of color</td>
<td style="text-align: right;">1.88</td>
<td style="text-align: right;">1.110</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">0.115</td>
</tr>
</tbody>
</table>
<p>The observed difference is:</p>
<p><span class="math display">\[
2.63 - 1.88 = 0.75
\]</span></p>
<p>The standard error for the difference is:</p>
<p><span class="math display">\[
SE =
\sqrt{0.073^2 + 0.115^2}
\]</span></p>
<p><span class="math display">\[
SE \approx 0.136
\]</span></p>
<p>So the estimated difference is:</p>
<p><span class="math display">\[
0.75
\]</span></p>
<p>with a standard error of about:</p>
<p><span class="math display">\[
0.136
\]</span></p>
<p>That difference is large relative to the standard error.</p>
<hr>
</section>
<section id="confidence-interval-for-the-difference" class="level2" data-number="13.8">
<h2 data-number="13.8" class="anchored" data-anchor-id="confidence-interval-for-the-difference"><span class="header-section-number">13.8</span> Confidence Interval for the Difference</h2>
<p>Suppose software gives a t critical value of approximately:</p>
<p><span class="math display">\[
t^* = 1.973
\]</span></p>
<p>Then the 95 percent confidence interval is:</p>
<p><span class="math display">\[
0.75 \pm 1.973(0.136)
\]</span></p>
<p><span class="math display">\[
0.75 \pm 0.268
\]</span></p>
<p>Lower bound:</p>
<p><span class="math display">\[
0.75 - 0.268 = 0.482
\]</span></p>
<p>Upper bound:</p>
<p><span class="math display">\[
0.75 + 0.268 = 1.018
\]</span></p>
<p>So the confidence interval is approximately:</p>
<p><span class="math display">\[
0.48 \text{ to } 1.02
\]</span></p>
<p>Interpretation:</p>
<blockquote class="blockquote">
<p>Across repeated samples, 95 percent of confidence intervals constructed using this procedure would contain the true difference in mean arrest rate ratios. In this sample, the interval ranges from about 0.48 to 1.02.</p>
</blockquote>
<p>Because the interval does not include 0, we expect to reject the null hypothesis of no difference.</p>
<hr>
</section>
<section id="significance-test-for-the-difference-of-means" class="level2" data-number="13.9">
<h2 data-number="13.9" class="anchored" data-anchor-id="significance-test-for-the-difference-of-means"><span class="header-section-number">13.9</span> Significance Test for the Difference of Means</h2>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \mu_2 - \mu_1 = 0
\]</span></p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[
H_A: \mu_2 - \mu_1 \neq 0
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{(\bar{Y}_2 - \bar{Y}_1) - 0}
{SE_{\bar{Y}_2-\bar{Y}_1}}
\]</span></p>
<p>Substitute values:</p>
<p><span class="math display">\[
t = \frac{0.75}{0.136}
\]</span></p>
<p><span class="math display">\[
t \approx 5.52
\]</span></p>
<p>This is far larger than a typical 95 percent critical value near 2.</p>
<p>Therefore, we reject the null hypothesis.</p>
<p>There is statistically significant evidence that mean arrest rate ratios differ between cities with majority white city councils and cities with majority persons of color city councils.</p>
<hr>
</section>
<section id="statistical-significance-is-not-causality" class="level2" data-number="13.10">
<h2 data-number="13.10" class="anchored" data-anchor-id="statistical-significance-is-not-causality"><span class="header-section-number">13.10</span> Statistical Significance Is Not Causality</h2>
<p>The difference is statistically significant.</p>
<p>But statistical significance does not prove causality.</p>
<p>This is an observational study. City council composition was not randomly assigned. Cities with majority white councils may differ from cities with majority persons of color councils in many ways.</p>
<p>Possible confounders include:</p>
<ul>
<li>city size</li>
<li>racial composition of the population</li>
<li>poverty rates</li>
<li>homelessness rates</li>
<li>policing strategies</li>
<li>police department demographics</li>
<li>local ordinances</li>
<li>neighborhood segregation</li>
<li>council election systems</li>
<li>regional political history</li>
<li>length of time with a racially diverse council</li>
</ul>
<p>The difference-of-means test establishes that the means differ in the sample, and likely in the broader population represented by the sample. It does not by itself establish that council composition caused the difference.</p>
<p>To strengthen causal claims, researchers may use methods such as statistical controls, regression, matching, panel data, qualitative case studies, or quasi-experimental designs.</p>
<hr>
</section>
</section>
<section id="part-iii-another-difference-of-means-example" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Part III: Another Difference-of-Means Example</h1>
<section id="democracies-and-infant-mortality" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="democracies-and-infant-mortality"><span class="header-section-number">14.1</span> Democracies and Infant Mortality</h2>
<p>Suppose we want to compare infant mortality in democracies and non-democracies.</p>
<p>Infant mortality is measured as deaths before age one per 1,000 live births.</p>
<p>The data are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Regime Type</th>
<th style="text-align: right;">Mean Infant Mortality</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Non-democracy</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: right;">28.2</td>
<td style="text-align: right;">75</td>
</tr>
<tr class="even">
<td>Democracy</td>
<td style="text-align: right;">20.7</td>
<td style="text-align: right;">21.9</td>
<td style="text-align: right;">101</td>
</tr>
</tbody>
</table>
<p>The observed difference is:</p>
<p><span class="math display">\[
40.0 - 20.7 = 19.3
\]</span></p>
<p>Infant mortality is about 19.3 deaths per 1,000 births higher in non-democracies than in democracies.</p>
<hr>
</section>
<section id="checking-assumptions" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="checking-assumptions"><span class="header-section-number">14.2</span> Checking Assumptions</h2>
<p>These are independent samples. Democracies and non-democracies are different groups of countries.</p>
<p>We should not automatically assume equal variances. Infant mortality may vary differently across democracies and non-democracies. In fact, non-democracies may include both very high-performing and very low-performing states, creating greater variation.</p>
<p>So we proceed with the independent-samples difference-of-means test without assuming equal variances.</p>
<p>Using the conservative degrees of freedom approximation:</p>
<p><span class="math display">\[
df = \min(75-1, 101-1)
\]</span></p>
<p><span class="math display">\[
df = \min(74, 100)
\]</span></p>
<p><span class="math display">\[
df = 74
\]</span></p>
<hr>
</section>
<section id="standard-error-for-the-difference" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="standard-error-for-the-difference"><span class="header-section-number">14.3</span> Standard Error for the Difference</h2>
<p>Use:</p>
<p><span class="math display">\[
SE =
\sqrt{
\frac{s_1^2}{n_1}
+
\frac{s_2^2}{n_2}
}
\]</span></p>
<p>Substitute values:</p>
<p><span class="math display">\[
SE =
\sqrt{
\frac{28.2^2}{75}
+
\frac{21.9^2}{101}
}
\]</span></p>
<p><span class="math display">\[
SE \approx 3.92
\]</span></p>
<p>So the observed difference is:</p>
<p><span class="math display">\[
19.3
\]</span></p>
<p>with a standard error of:</p>
<p><span class="math display">\[
3.92
\]</span></p>
<hr>
</section>
<section id="confidence-interval" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="confidence-interval"><span class="header-section-number">14.4</span> Confidence Interval</h2>
<p>Using the conservative degrees of freedom and a 95 percent confidence interval, suppose the t critical value is approximately:</p>
<p><span class="math display">\[
t^* = 2.00
\]</span></p>
<p>Then:</p>
<p><span class="math display">\[
19.3 \pm 2.00(3.92)
\]</span></p>
<p><span class="math display">\[
19.3 \pm 7.84
\]</span></p>
<p>Lower bound:</p>
<p><span class="math display">\[
19.3 - 7.84 = 11.46
\]</span></p>
<p>Upper bound:</p>
<p><span class="math display">\[
19.3 + 7.84 = 27.14
\]</span></p>
<p>The 95 percent confidence interval is approximately:</p>
<p><span class="math display">\[
11.5 \text{ to } 27.1
\]</span></p>
<p>The interval does not include 0, suggesting a statistically significant difference.</p>
<hr>
</section>
<section id="significance-test" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="significance-test"><span class="header-section-number">14.5</span> Significance Test</h2>
<p>The hypotheses are:</p>
<p><span class="math display">\[
H_0: \mu_{non-democracy} - \mu_{democracy} = 0
\]</span></p>
<p><span class="math display">\[
H_A: \mu_{non-democracy} - \mu_{democracy} \neq 0
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{19.3 - 0}{3.92}
\]</span></p>
<p><span class="math display">\[
t \approx 4.92
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
4.92 &gt; 2.00
\]</span></p>
<p>we reject the null hypothesis.</p>
<p>There is statistically significant evidence that mean infant mortality differs between democracies and non-democracies.</p>
<p>Again, causality requires further analysis. Democracies and non-democracies differ in wealth, institutions, health systems, conflict exposure, education, and many other factors.</p>
<hr>
</section>
</section>
<section id="part-iv-difference-of-proportions-tests" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Part IV: Difference-of-Proportions Tests</h1>
<section id="comparing-two-proportions" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="comparing-two-proportions"><span class="header-section-number">15.1</span> Comparing Two Proportions</h2>
<p>A difference-of-proportions test compares the proportion in one group to the proportion in another group.</p>
<p>Examples:</p>
<ul>
<li>graduation rates among program participants versus nonparticipants</li>
<li>vaccination rates in treatment and control groups</li>
<li>support for a policy among Democrats and Republicans</li>
<li>employment rates among those who completed training and those who did not</li>
</ul>
<p>The population parameters are:</p>
<p><span class="math display">\[
\pi_1
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
\pi_2
\]</span></p>
<p>The sample estimates are:</p>
<p><span class="math display">\[
\hat{\pi}_1
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
\hat{\pi}_2
\]</span></p>
<p>The null hypothesis is usually:</p>
<p><span class="math display">\[
H_0: \pi_2 - \pi_1 = 0
\]</span></p>
<p>or equivalently:</p>
<p><span class="math display">\[
H_0: \pi_1 = \pi_2
\]</span></p>
<p>The alternative is:</p>
<p><span class="math display">\[
H_A: \pi_2 - \pi_1 \neq 0
\]</span></p>
<hr>
</section>
<section id="sample-size-rule-for-difference-of-proportions" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="sample-size-rule-for-difference-of-proportions"><span class="header-section-number">15.2</span> Sample Size Rule for Difference of Proportions</h2>
<p>To use the z-test for a difference of proportions, each of the four cells should have at least about 10 cases.</p>
<p>Why four cells?</p>
<p>Because we have:</p>
<ol type="1">
<li>group 1, in the category</li>
<li>group 1, not in the category</li>
<li>group 2, in the category</li>
<li>group 2, not in the category</li>
</ol>
<p>For example, if comparing graduation rates among program participants and nonparticipants, we need at least 10 cases in each of:</p>
<ul>
<li>participants who graduated</li>
<li>participants who did not graduate</li>
<li>nonparticipants who graduated</li>
<li>nonparticipants who did not graduate</li>
</ul>
<p>If this rule is not met, the z-test may not be appropriate.</p>
<hr>
</section>
<section id="example-graduation-program" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="example-graduation-program"><span class="header-section-number">15.3</span> Example: Graduation Program</h2>
<p>Suppose we evaluate a program intended to increase high school graduation.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Graduated</th>
<th style="text-align: right;">Did Not Graduate</th>
<th style="text-align: right;">Total</th>
<th style="text-align: right;">Graduation Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Program</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">93</td>
<td style="text-align: right;">0.892</td>
</tr>
<tr class="even">
<td>No Program</td>
<td style="text-align: right;">102</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">121</td>
<td style="text-align: right;">0.843</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">185</td>
<td style="text-align: right;">29</td>
<td style="text-align: right;">214</td>
<td style="text-align: right;">0.864</td>
</tr>
</tbody>
</table>
<p>The sample proportions are:</p>
<p><span class="math display">\[
\hat{\pi}_{program} = \frac{83}{93} = 0.892
\]</span></p>
<p><span class="math display">\[
\hat{\pi}_{no\ program} = \frac{102}{121} = 0.843
\]</span></p>
<p>The observed difference is:</p>
<p><span class="math display">\[
0.892 - 0.843 = 0.049
\]</span></p>
<p>The program group has a graduation rate about 4.9 percentage points higher than the no-program group.</p>
<hr>
</section>
<section id="confidence-interval-for-a-difference-of-proportions" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="confidence-interval-for-a-difference-of-proportions"><span class="header-section-number">15.4</span> Confidence Interval for a Difference of Proportions</h2>
<p>For a confidence interval, we use the two sample proportions separately.</p>
<p>The standard error is:</p>
<p><span class="math display">\[
SE =
\sqrt{
\frac{\hat{\pi}_1(1-\hat{\pi}_1)}{n_1}
+
\frac{\hat{\pi}_2(1-\hat{\pi}_2)}{n_2}
}
\]</span></p>
<p>The confidence interval is:</p>
<p><span class="math display">\[
(\hat{\pi}_2 - \hat{\pi}_1)
\pm
z^*
SE
\]</span></p>
<p>Using the example:</p>
<p><span class="math display">\[
0.049 \pm 1.96
\sqrt{
\frac{0.843(1-0.843)}{121}
+
\frac{0.892(1-0.892)}{93}
}
\]</span></p>
<p>The margin of error is approximately:</p>
<p><span class="math display">\[
0.09
\]</span></p>
<p>So the confidence interval is:</p>
<p><span class="math display">\[
0.049 \pm 0.09
\]</span></p>
<p>Lower bound:</p>
<p><span class="math display">\[
0.049 - 0.09 = -0.041
\]</span></p>
<p>Upper bound:</p>
<p><span class="math display">\[
0.049 + 0.09 = 0.139
\]</span></p>
<p>So the 95 percent confidence interval is approximately:</p>
<p><span class="math display">\[
-0.04 \text{ to } 0.14
\]</span></p>
<p>Because the interval includes 0, we expect not to reject the null hypothesis of no difference.</p>
<hr>
</section>
<section id="why-can-the-confidence-interval-include-negative-values" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="why-can-the-confidence-interval-include-negative-values"><span class="header-section-number">15.5</span> Why Can the Confidence Interval Include Negative Values?</h2>
<p>A difference of proportions can be negative.</p>
<p>If the program group has a lower graduation rate than the no-program group, then:</p>
<p><span class="math display">\[
\hat{\pi}_{program} - \hat{\pi}_{no\ program} &lt; 0
\]</span></p>
<p>So a confidence interval for a difference can cross 0.</p>
<p>A confidence interval that includes 0 means that no difference is a plausible value. In such a case, we generally fail to reject the null hypothesis.</p>
<hr>
</section>
<section id="significance-test-for-difference-of-proportions" class="level2" data-number="15.6">
<h2 data-number="15.6" class="anchored" data-anchor-id="significance-test-for-difference-of-proportions"><span class="header-section-number">15.6</span> Significance Test for Difference of Proportions</h2>
<p>For a significance test, the standard error is calculated differently than for a confidence interval.</p>
<p>Under the null hypothesis:</p>
<p><span class="math display">\[
\pi_1 = \pi_2
\]</span></p>
<p>So we assume there is one common population proportion.</p>
<p>We estimate that common proportion using the pooled sample proportion:</p>
<p><span class="math display">\[
\hat{\pi} =
\frac{x_1+x_2}{n_1+n_2}
\]</span></p>
<p>In the graduation example:</p>
<p><span class="math display">\[
\hat{\pi} = \frac{83+102}{93+121}
\]</span></p>
<p><span class="math display">\[
\hat{\pi} = \frac{185}{214}
\]</span></p>
<p><span class="math display">\[
\hat{\pi} = 0.864
\]</span></p>
<p>The null-hypothesis standard error is:</p>
<p><span class="math display">\[
SE_0 =
\sqrt{
\hat{\pi}(1-\hat{\pi})
\left(
\frac{1}{n_1}+\frac{1}{n_2}
\right)
}
\]</span></p>
<p>Equivalently:</p>
<p><span class="math display">\[
SE_0 =
\sqrt{
\frac{\hat{\pi}(1-\hat{\pi})}{n_1}
+
\frac{\hat{\pi}(1-\hat{\pi})}{n_2}
}
\]</span></p>
<p>Using the example:</p>
<p><span class="math display">\[
SE_0 \approx 0.047
\]</span></p>
<hr>
</section>
<section id="z-test-for-difference-of-proportions" class="level2" data-number="15.7">
<h2 data-number="15.7" class="anchored" data-anchor-id="z-test-for-difference-of-proportions"><span class="header-section-number">15.7</span> z-Test for Difference of Proportions</h2>
<p>The z-statistic is:</p>
<p><span class="math display">\[
z =
\frac{(\hat{\pi}_2-\hat{\pi}_1)-0}
{SE_0}
\]</span></p>
<p>Using the observed difference:</p>
<p><span class="math display">\[
z =
\frac{0.049}{0.047}
\]</span></p>
<p><span class="math display">\[
z \approx 1.04
\]</span></p>
<p>The critical value for a two-tailed test with <span class="math inline">\(\alpha = 0.05\)</span> is:</p>
<p><span class="math display">\[
1.96
\]</span></p>
<p>Since:</p>
<p><span class="math display">\[
1.04 &lt; 1.96
\]</span></p>
<p>we fail to reject the null hypothesis.</p>
<p>There is not statistically significant evidence at the 0.05 level that the program changed graduation rates.</p>
<hr>
</section>
</section>
<section id="part-v-dependent-samples" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> Part V: Dependent Samples</h1>
<section id="what-are-dependent-samples" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="what-are-dependent-samples"><span class="header-section-number">16.1</span> What Are Dependent Samples?</h2>
<p>Samples are <strong>dependent</strong> when cases in one sample are explicitly matched with cases in the other sample.</p>
<p>Common examples include:</p>
<ul>
<li>before-and-after measurements of the same people</li>
<li>twins split across treatment and control</li>
<li>matched pairs of similar people or places</li>
<li>households measured before and after an intervention</li>
</ul>
<p>In dependent samples, the two observations are linked.</p>
<p>This changes the analysis.</p>
<p>Instead of comparing two independent group means, we compare differences within pairs.</p>
<hr>
</section>
<section id="turning-a-two-sample-problem-into-a-one-sample-problem" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="turning-a-two-sample-problem-into-a-one-sample-problem"><span class="header-section-number">16.2</span> Turning a Two-Sample Problem into a One-Sample Problem</h2>
<p>With dependent samples, we create a new variable:</p>
<p><span class="math display">\[
Y_d = Y_2 - Y_1
\]</span></p>
<p>This is the difference for each matched pair.</p>
<p>Then we analyze the mean of those differences:</p>
<p><span class="math display">\[
\bar{Y}_d
\]</span></p>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \mu_d = 0
\]</span></p>
<p>where <span class="math inline">\(\mu_d\)</span> is the population mean of the paired differences.</p>
<p>The alternative is:</p>
<p><span class="math display">\[
H_A: \mu_d \neq 0
\]</span></p>
<p>This is now a one-sample test on the difference variable.</p>
<hr>
</section>
<section id="example-matched-pairs" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="example-matched-pairs"><span class="header-section-number">16.3</span> Example: Matched Pairs</h2>
<p>Suppose we have four matched pairs:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Pair</th>
<th style="text-align: right;"><span class="math inline">\(Y_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(Y_1\)</span></th>
<th style="text-align: right;">Difference <span class="math inline">\(Y_d = Y_2-Y_1\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">-1</td>
</tr>
</tbody>
</table>
<p>The mean of the differences is:</p>
<p><span class="math display">\[
\bar{Y}_d = \frac{2+0+2-1}{4}
\]</span></p>
<p><span class="math display">\[
\bar{Y}_d = 0.75
\]</span></p>
<p>The mean of <span class="math inline">\(Y_2\)</span> is:</p>
<p><span class="math display">\[
\bar{Y}_2 = 4.5
\]</span></p>
<p>The mean of <span class="math inline">\(Y_1\)</span> is:</p>
<p><span class="math display">\[
\bar{Y}_1 = 3.75
\]</span></p>
<p>The difference of the means is:</p>
<p><span class="math display">\[
4.5 - 3.75 = 0.75
\]</span></p>
<p>So:</p>
<p><span class="math display">\[
\bar{Y}_d = \bar{Y}_2 - \bar{Y}_1
\]</span></p>
<p>The mean of the differences equals the difference of the means.</p>
<p>The advantage of the dependent-samples approach is that it uses the pairing information.</p>
<hr>
</section>
<section id="standard-error-for-dependent-samples" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="standard-error-for-dependent-samples"><span class="header-section-number">16.4</span> Standard Error for Dependent Samples</h2>
<p>For dependent samples, calculate the standard deviation of the difference variable:</p>
<p><span class="math display">\[
s_d
\]</span></p>
<p>Then the standard error is:</p>
<p><span class="math display">\[
SE_{\bar{Y}_d} = \frac{s_d}{\sqrt{n}}
\]</span></p>
<p>where <span class="math inline">\(n\)</span> is the number of matched pairs.</p>
<p>The confidence interval is:</p>
<p><span class="math display">\[
\bar{Y}_d \pm t^*\left(\frac{s_d}{\sqrt{n}}\right)
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{\bar{Y}_d - 0}
{s_d/\sqrt{n}}
\]</span></p>
<p>Degrees of freedom are:</p>
<p><span class="math display">\[
df = n - 1
\]</span></p>
<p>This is simply a one-sample t-test on the paired differences.</p>
<hr>
</section>
<section id="example-lead-pipe-replacement" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="example-lead-pipe-replacement"><span class="header-section-number">16.5</span> Example: Lead Pipe Replacement</h2>
<p>Suppose a city replaces lead water supply lines.</p>
<p>Researchers select 250 households. They measure lead levels before the replacement and again after the replacement.</p>
<p>For each household:</p>
<p><span class="math display">\[
Y_d = \text{lead after} - \text{lead before}
\]</span></p>
<p>Suppose the mean difference is:</p>
<p><span class="math display">\[
\bar{Y}_d = -3.2
\]</span></p>
<p>parts per billion. This means lead levels fell by 3.2 parts per billion on average.</p>
<p>Suppose the standard deviation of differences is:</p>
<p><span class="math display">\[
s_d = 23.7
\]</span></p>
<p>and:</p>
<p><span class="math display">\[
n = 250
\]</span></p>
<p>The standard error is:</p>
<p><span class="math display">\[
SE = \frac{23.7}{\sqrt{250}}
\]</span></p>
<p><span class="math display">\[
SE \approx 1.50
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{-3.2 - 0}{1.50}
\]</span></p>
<p><span class="math display">\[
t \approx -2.13
\]</span></p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df = 249
\]</span></p>
<p>The critical value for a two-tailed 95 percent test is close to 1.97.</p>
<p>Since:</p>
<p><span class="math display">\[
|-2.13| &gt; 1.97
\]</span></p>
<p>we reject the null hypothesis.</p>
<p>There is statistically significant evidence that lead levels changed. Because the mean difference is negative, the evidence suggests lead levels decreased after pipe replacement.</p>
<hr>
</section>
</section>
<section id="part-vi-equal-variance-assumption" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Part VI: Equal Variance Assumption</h1>
<section id="what-is-the-equal-variance-assumption" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="what-is-the-equal-variance-assumption"><span class="header-section-number">17.1</span> What Is the Equal Variance Assumption?</h2>
<p>In an independent-samples difference-of-means test, we sometimes assume that the two populations have equal variances:</p>
<p><span class="math display">\[
\sigma_1^2 = \sigma_2^2
\]</span></p>
<p>This is called the <strong>equal variance assumption</strong>.</p>
<p>If the assumption is true, the two sample variances estimate the same underlying population variance. We can pool them together to estimate one common variance.</p>
<p>This can be useful, especially when sample sizes are small, because pooling uses information more efficiently.</p>
<p>But the assumption can be dangerous if it is wrong.</p>
<hr>
</section>
<section id="when-might-equal-variances-be-plausible" class="level2" data-number="17.2">
<h2 data-number="17.2" class="anchored" data-anchor-id="when-might-equal-variances-be-plausible"><span class="header-section-number">17.2</span> When Might Equal Variances Be Plausible?</h2>
<p>Equal variances may be plausible when the two groups are very similar except for treatment assignment.</p>
<p>For example, in a randomized experiment, treatment and control groups come from the same sample and are randomly assigned. It may be reasonable to assume that the outcome variable has similar variance in both groups.</p>
<p>Another possible example: a teacher compares test scores from two successive third-grade classes taught in the same school, assuming the student populations are similar from year to year.</p>
<p>But even these examples require caution. An intervention might affect not only the mean but also the variance. For instance, a teaching method might help lower-performing students more than higher-performing students, reducing variation.</p>
<p>The equal variance assumption is theoretical. We do not know population variances, so we cannot truly verify it with certainty.</p>
<hr>
</section>
<section id="why-the-assumption-matters" class="level2" data-number="17.3">
<h2 data-number="17.3" class="anchored" data-anchor-id="why-the-assumption-matters"><span class="header-section-number">17.3</span> Why the Assumption Matters</h2>
<p>Without assuming equal variances, the standard error is:</p>
<p><span class="math display">\[
SE =
\sqrt{
\frac{s_1^2}{n_1}
+
\frac{s_2^2}{n_2}
}
\]</span></p>
<p>Degrees of freedom are estimated using the Satterthwaite formula or a conservative approximation.</p>
<p>With equal variances, we pool the variances and use:</p>
<p><span class="math display">\[
df = n_1+n_2-2
\]</span></p>
<p>This gives the maximum possible degrees of freedom.</p>
<p>More degrees of freedom generally means a smaller critical value, making it easier to reject the null hypothesis.</p>
<p>Therefore, if the equal variance assumption is wrong, using it can increase the risk of an incorrect conclusion.</p>
<hr>
</section>
<section id="pooled-standard-deviation" class="level2" data-number="17.4">
<h2 data-number="17.4" class="anchored" data-anchor-id="pooled-standard-deviation"><span class="header-section-number">17.4</span> Pooled Standard Deviation</h2>
<p>When assuming equal variances, we calculate a pooled variance:</p>
<p><span class="math display">\[
s_p^2 =
\frac{
(n_1-1)s_1^2 + (n_2-1)s_2^2
}
{
n_1+n_2-2
}
\]</span></p>
<p>Then take the square root:</p>
<p><span class="math display">\[
s_p = \sqrt{s_p^2}
\]</span></p>
<p>This is a weighted average of the two sample variances, weighted by their degrees of freedom.</p>
<p>The larger sample contributes more to the pooled estimate.</p>
<hr>
</section>
<section id="standard-error-with-equal-variances" class="level2" data-number="17.5">
<h2 data-number="17.5" class="anchored" data-anchor-id="standard-error-with-equal-variances"><span class="header-section-number">17.5</span> Standard Error with Equal Variances</h2>
<p>Once we have the pooled standard deviation, the standard error for the difference of means is:</p>
<p><span class="math display">\[
SE =
s_p
\sqrt{
\frac{1}{n_1}+\frac{1}{n_2}
}
\]</span></p>
<p>The confidence interval is:</p>
<p><span class="math display">\[
(\bar{Y}_2-\bar{Y}_1)
\pm
t^*s_p
\sqrt{
\frac{1}{n_1}+\frac{1}{n_2}
}
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{(\bar{Y}_2-\bar{Y}_1)-0}
{s_p
\sqrt{
\frac{1}{n_1}+\frac{1}{n_2}
}}
\]</span></p>
<p>Degrees of freedom are:</p>
<p><span class="math display">\[
df = n_1+n_2-2
\]</span></p>
<hr>
</section>
<section id="example-temperatures-in-ann-arbor" class="level2" data-number="17.6">
<h2 data-number="17.6" class="anchored" data-anchor-id="example-temperatures-in-ann-arbor"><span class="header-section-number">17.6</span> Example: Temperatures in Ann Arbor</h2>
<p>Suppose we compare mean temperatures in Ann Arbor in 1900 and 2000.</p>
<p>Imagine the data are:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Year</th>
<th style="text-align: right;">Mean Temperature</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1900</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="even">
<td>2000</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">366</td>
</tr>
</tbody>
</table>
<p>The observed difference is:</p>
<p><span class="math display">\[
50 - 47 = 3
\]</span></p>
<p>Suppose we make the equal variance assumption. That means we assume the variance of daily temperatures is the same in 1900 and 2000.</p>
<p>This may or may not be reasonable. If climate change affects not only average temperature but also variability, the assumption may fail.</p>
<p>Still, for illustration, calculate the pooled standard deviation.</p>
<hr>
</section>
<section id="pooled-standard-deviation-calculation" class="level2" data-number="17.7">
<h2 data-number="17.7" class="anchored" data-anchor-id="pooled-standard-deviation-calculation"><span class="header-section-number">17.7</span> Pooled Standard Deviation Calculation</h2>
<p>Use:</p>
<p><span class="math display">\[
s_p^2 =
\frac{
(15-1)(14^2) + (366-1)(11^2)
}
{
15+366-2
}
\]</span></p>
<p><span class="math display">\[
s_p^2 =
\frac{
14(196)+365(121)
}
{379}
\]</span></p>
<p><span class="math display">\[
s_p \approx 11.3
\]</span></p>
<p>Now calculate the standard error:</p>
<p><span class="math display">\[
SE =
11.3
\sqrt{
\frac{1}{15}+\frac{1}{366}
}
\]</span></p>
<p><span class="math display">\[
SE \approx 2.93
\]</span></p>
<p>The t-statistic is:</p>
<p><span class="math display">\[
t =
\frac{3}{2.93}
\]</span></p>
<p><span class="math display">\[
t \approx 1.02
\]</span></p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df = 15+366-2 = 379
\]</span></p>
<p>The critical value is close to 1.96.</p>
<p>Since:</p>
<p><span class="math display">\[
1.02 &lt; 1.96
\]</span></p>
<p>we fail to reject the null hypothesis.</p>
<p>There is not statistically significant evidence, in this illustrative example, that mean temperature changed.</p>
<hr>
</section>
</section>
<section id="part-vii-small-sample-alternatives" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Part VII: Small-Sample Alternatives</h1>
<section id="when-the-usual-tests-do-not-work" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="when-the-usual-tests-do-not-work"><span class="header-section-number">18.1</span> When the Usual Tests Do Not Work</h2>
<p>The usual t-tests and z-tests rely on assumptions.</p>
<p>For means, if samples are small and the population is not normal, the t-test may not be appropriate.</p>
<p>For proportions, if cell counts are too small, the z-test may not be appropriate.</p>
<p>When those assumptions fail, we can use non-parametric or exact tests.</p>
<p>These tests often go directly to a p-value rather than using a t or z statistic.</p>
<hr>
</section>
<section id="fishers-exact-test-for-small-sample-proportions" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="fishers-exact-test-for-small-sample-proportions"><span class="header-section-number">18.2</span> Fisher’s Exact Test for Small-Sample Proportions</h2>
<p>When comparing two proportions, if any of the four cells has fewer than about 10 cases, use Fisher’s exact test rather than the z-test.</p>
<p>Fisher’s exact test evaluates how unusual the observed table is under the null hypothesis of no association.</p>
<p>It holds the row and column totals fixed and considers all possible tables with those totals. It then asks what proportion of those possible tables are as extreme as, or more extreme than, the observed table.</p>
<p>That proportion is the p-value.</p>
<hr>
</section>
<section id="example-sleep-and-masters-students" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="example-sleep-and-masters-students"><span class="header-section-number">18.3</span> Example: Sleep and Master’s Students</h2>
<p>Suppose we ask whether people get enough sleep.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Group</th>
<th style="text-align: right;">Enough Sleep</th>
<th style="text-align: right;">Not Enough Sleep</th>
<th style="text-align: right;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Master’s students</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td>Other young professionals</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>
<p>Several cells have fewer than 10 cases, so a z-test for difference of proportions is not appropriate.</p>
<p>Use Fisher’s exact test.</p>
<p>Suppose Fisher’s exact test gives:</p>
<p><span class="math display">\[
p = 0.056
\]</span></p>
<p>At:</p>
<p><span class="math display">\[
\alpha = 0.05
\]</span></p>
<p>we fail to reject the null hypothesis.</p>
<p>At:</p>
<p><span class="math display">\[
\alpha = 0.10
\]</span></p>
<p>we would reject.</p>
<p>The result suggests evidence of a difference, but not quite enough for the conventional 0.05 threshold.</p>
<hr>
</section>
<section id="wilcoxon-mann-whitney-test-for-small-sample-independent-means" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="wilcoxon-mann-whitney-test-for-small-sample-independent-means"><span class="header-section-number">18.4</span> Wilcoxon-Mann-Whitney Test for Small-Sample Independent Means</h2>
<p>When comparing two means with independent samples, if samples are small and population normality cannot be assumed, use a non-parametric alternative.</p>
<p>One option is the <strong>Wilcoxon-Mann-Whitney test</strong>.</p>
<p>This test does not compare means directly. Instead, it ranks all observations from both groups together and examines whether one group tends to have higher ranks than the other.</p>
<p>It is useful when:</p>
<ul>
<li>the outcome is at least ordinal</li>
<li>samples are independent</li>
<li>sample sizes are small</li>
<li>the normality assumption is not plausible</li>
</ul>
<hr>
</section>
<section id="example-democracy-and-gdp-per-capita" class="level2" data-number="18.5">
<h2 data-number="18.5" class="anchored" data-anchor-id="example-democracy-and-gdp-per-capita"><span class="header-section-number">18.5</span> Example: Democracy and GDP per Capita</h2>
<p>Suppose we compare GDP per capita in democracies and non-democracies in Latin America in 1975.</p>
<p>There are only 24 countries:</p>
<ul>
<li>12 democracies</li>
<li>12 non-democracies</li>
</ul>
<p>GDP per capita is skewed, so the population normality assumption is not plausible. A standard t-test may not be appropriate.</p>
<p>The Wilcoxon-Mann-Whitney test ranks all 24 countries by GDP per capita and compares the rank positions of democracies and non-democracies.</p>
<p>If the two groups are similar, their ranks should be mixed. If one group tends to have higher GDP per capita, that group should have systematically higher ranks.</p>
<p>Suppose the test gives:</p>
<p><span class="math display">\[
p = 0.67
\]</span></p>
<p>This is large, so we fail to reject the null hypothesis.</p>
<p>There is no statistically significant evidence that GDP per capita differs between democracies and non-democracies in this small sample.</p>
<hr>
</section>
<section id="wilcoxon-signed-rank-test-for-dependent-samples" class="level2" data-number="18.6">
<h2 data-number="18.6" class="anchored" data-anchor-id="wilcoxon-signed-rank-test-for-dependent-samples"><span class="header-section-number">18.6</span> Wilcoxon Signed-Rank Test for Dependent Samples</h2>
<p>For dependent samples, if the sample is small and the population of differences is not normally distributed, use the <strong>Wilcoxon signed-rank test</strong>.</p>
<p>This is the non-parametric counterpart to the paired t-test.</p>
<p>It uses the ranks of the paired differences rather than assuming the differences are normally distributed.</p>
<p>Use it when:</p>
<ul>
<li>samples are paired</li>
<li>the outcome is at least ordinal</li>
<li>the sample size is small</li>
<li>the distribution of differences is not plausibly normal</li>
</ul>
<p>The details are less important here than knowing when the test is appropriate.</p>
<hr>
</section>
</section>
<section id="part-viii-controlled-comparisons-of-means" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> Part VIII: Controlled Comparisons of Means</h1>
<section id="why-add-a-control-variable" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="why-add-a-control-variable"><span class="header-section-number">19.1</span> Why Add a Control Variable?</h2>
<p>When comparing group means using observational data, groups may differ in more than one way.</p>
<p>Suppose we compare life expectancy in democracies and non-democracies.</p>
<p>If democracies have higher life expectancy, is that because they are democracies?</p>
<p>Maybe. But democracies also tend to be wealthier. Wealthier countries usually have better health systems, nutrition, infrastructure, and education.</p>
<p>So country wealth may confound the relationship between democracy and life expectancy.</p>
<p>To address this, we can introduce a control variable.</p>
<p>A <strong>control variable</strong> is a variable we hold constant while examining the relationship between an independent variable and an outcome.</p>
<hr>
</section>
<section id="controlling-in-a-mean-comparison-table" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="controlling-in-a-mean-comparison-table"><span class="header-section-number">19.2</span> Controlling in a Mean Comparison Table</h2>
<p>Suppose:</p>
<ul>
<li><span class="math inline">\(Y\)</span>: life expectancy</li>
<li><span class="math inline">\(X\)</span>: democracy status</li>
<li><span class="math inline">\(Z\)</span>: GDP per capita category</li>
</ul>
<p>We can compare mean life expectancy across democracy categories while holding GDP per capita constant.</p>
<p>For example, divide countries into:</p>
<ul>
<li>low GDP per capita</li>
<li>middle GDP per capita</li>
<li>high GDP per capita</li>
</ul>
<p>Then compare democracies and non-democracies within each income category.</p>
<hr>
</section>
<section id="example-democracy-wealth-and-life-expectancy" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="example-democracy-wealth-and-life-expectancy"><span class="header-section-number">19.3</span> Example: Democracy, Wealth, and Life Expectancy</h2>
<p>Suppose the table is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime Type</th>
<th style="text-align: right;">Low GDP</th>
<th style="text-align: right;">Middle GDP</th>
<th style="text-align: right;">High GDP</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Non-democracy</td>
<td style="text-align: right;">57.8</td>
<td style="text-align: right;">68.7</td>
<td style="text-align: right;">73.5</td>
<td style="text-align: right;">64.5</td>
</tr>
<tr class="even">
<td>Democracy</td>
<td style="text-align: right;">63.3</td>
<td style="text-align: right;">74.1</td>
<td style="text-align: right;">79.2</td>
<td style="text-align: right;">72.5</td>
</tr>
</tbody>
</table>
<p>The overall comparison suggests democracies have higher life expectancy:</p>
<p><span class="math display">\[
72.5 - 64.5 = 8.0
\]</span></p>
<p>But we also compare within GDP categories.</p>
<p>Low-income countries:</p>
<p><span class="math display">\[
63.3 - 57.8 = 5.5
\]</span></p>
<p>Middle-income countries:</p>
<p><span class="math display">\[
74.1 - 68.7 = 5.4
\]</span></p>
<p>High-income countries:</p>
<p><span class="math display">\[
79.2 - 73.5 = 5.7
\]</span></p>
<p>Even after controlling for GDP category, democracies still have higher life expectancy in each income group.</p>
<p>This suggests the relationship between democracy and life expectancy is not entirely explained by GDP per capita.</p>
<hr>
</section>
<section id="additive-relationships" class="level2" data-number="19.4">
<h2 data-number="19.4" class="anchored" data-anchor-id="additive-relationships"><span class="header-section-number">19.4</span> Additive Relationships</h2>
<p>An <strong>additive relationship</strong> occurs when two variables each appear to matter, and their effects are relatively consistent across categories of the other variable.</p>
<p>In the example, democracy is associated with higher life expectancy within each GDP category. GDP is also associated with higher life expectancy within each regime type.</p>
<p>Both democracy and GDP appear to matter.</p>
<p>The effect of democracy is similar across income categories. That is an additive pattern.</p>
<hr>
</section>
<section id="spurious-relationships" class="level2" data-number="19.5">
<h2 data-number="19.5" class="anchored" data-anchor-id="spurious-relationships"><span class="header-section-number">19.5</span> Spurious Relationships</h2>
<p>A relationship is <strong>spurious</strong> if it disappears after controlling for another variable.</p>
<p>Suppose democracies had higher life expectancy overall, but within each GDP category, democracies and non-democracies had the same life expectancy.</p>
<p>Then the original relationship between democracy and life expectancy would be spurious.</p>
<p>GDP per capita would explain the apparent relationship.</p>
<p>This is like the helium balloon example: the string appeared related to floating, but helium was the true cause.</p>
<hr>
</section>
<section id="interactive-relationships" class="level2" data-number="19.6">
<h2 data-number="19.6" class="anchored" data-anchor-id="interactive-relationships"><span class="header-section-number">19.6</span> Interactive Relationships</h2>
<p>An <strong>interactive relationship</strong> occurs when the effect of one variable changes depending on the value of another variable.</p>
<p>For example, suppose democracy has:</p>
<ul>
<li>little effect in low-income countries</li>
<li>moderate effect in middle-income countries</li>
<li>large effect in high-income countries</li>
</ul>
<p>Then the effect of democracy depends on GDP level.</p>
<p>That is an interaction.</p>
<p>In table form, interactions appear when differences across one variable vary substantially across categories of the control variable.</p>
<hr>
</section>
<section id="limits-of-controlled-mean-tables" class="level2" data-number="19.7">
<h2 data-number="19.7" class="anchored" data-anchor-id="limits-of-controlled-mean-tables"><span class="header-section-number">19.7</span> Limits of Controlled Mean Tables</h2>
<p>Controlled mean comparison tables are useful, but they have limits.</p>
<p>Adding one control variable can already create many cells. Adding two or three controls quickly makes the table unwieldy.</p>
<p>For example, if:</p>
<ul>
<li>democracy has 2 categories</li>
<li>GDP has 3 categories</li>
<li>region has 5 categories</li>
<li>colonial history has 4 categories</li>
</ul>
<p>the number of combinations becomes large very quickly.</p>
<p>This is one reason researchers use regression. Regression allows us to control for multiple variables more efficiently.</p>
<p>Mean comparison tables are helpful for building intuition, but regression is more practical for more complex analysis.</p>
<hr>
</section>
</section>
<section id="key-terms" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Key Terms</h1>
<p><strong>Mean comparison table</strong><br>
A table showing the mean of an interval-level variable across categories of another variable.</p>
<p><strong>Difference of means</strong><br>
The difference between two sample means.</p>
<p><strong>Independent samples</strong><br>
Samples in which observations in one group are not explicitly matched with observations in another group.</p>
<p><strong>Dependent samples</strong><br>
Samples in which observations are paired or matched across groups.</p>
<p><strong>Standard error of the difference</strong><br>
The standard error associated with a difference between two sample statistics.</p>
<p><strong>Difference-of-means test</strong><br>
A significance test evaluating whether two population means differ.</p>
<p><strong>Difference-of-proportions test</strong><br>
A significance test evaluating whether two population proportions differ.</p>
<p><strong>Equal variance assumption</strong><br>
The assumption that two populations have the same variance.</p>
<p><strong>Pooled standard deviation</strong><br>
A weighted estimate of a common standard deviation under the equal variance assumption.</p>
<p><strong>Satterthwaite approximation</strong><br>
A formula for estimating degrees of freedom in a two-sample t-test without assuming equal variances.</p>
<p><strong>Paired t-test</strong><br>
A t-test for dependent samples, based on the mean of paired differences.</p>
<p><strong>Fisher’s exact test</strong><br>
An exact test for association in small-sample categorical data.</p>
<p><strong>Wilcoxon-Mann-Whitney test</strong><br>
A non-parametric test for comparing two independent samples when normality cannot be assumed.</p>
<p><strong>Wilcoxon signed-rank test</strong><br>
A non-parametric test for comparing paired samples when normality of differences cannot be assumed.</p>
<p><strong>Control variable</strong><br>
A variable held constant to evaluate whether a relationship between two other variables persists.</p>
<p><strong>Additive relationship</strong><br>
A relationship in which two variables each have effects that are relatively consistent across categories of the other.</p>
<p><strong>Spurious relationship</strong><br>
An apparent relationship that disappears after controlling for another variable.</p>
<p><strong>Interactive relationship</strong><br>
A relationship in which the effect of one variable depends on the value of another variable.</p>
<hr>
</section>
<section id="chapter-summary" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> Chapter Summary</h1>
<p>Comparing two groups is central to statistical analysis. We often want to know whether two means or two proportions differ and whether those differences are statistically significant.</p>
<p>A mean comparison table provides a descriptive starting point. It shows how the mean of an interval-level variable differs across categories of another variable. But statistical significance requires a formal test.</p>
<p>For independent-sample difference-of-means tests, we compare two sample means and calculate a standard error for their difference. The standard error incorporates uncertainty from both sample means. We then use a t-test to determine whether the observed difference is large enough to reject the null hypothesis of no difference.</p>
<p>For difference-of-proportions tests, we compare two sample proportions. Confidence intervals use the two sample proportions separately, while significance tests use a pooled proportion under the null hypothesis.</p>
<p>Dependent samples require a different approach. When observations are paired, such as before-and-after measurements, we calculate differences within pairs and conduct a one-sample test on those differences.</p>
<p>Sometimes researchers assume equal variances across populations, allowing them to pool standard deviations and use more degrees of freedom. This can be useful but risky if the assumption is wrong.</p>
<p>When sample sizes are too small for standard parametric tests, exact or non-parametric alternatives are available. Fisher’s exact test is used for small-sample proportions. The Wilcoxon-Mann-Whitney and Wilcoxon signed-rank tests are used for small-sample comparisons of means or paired differences when normality assumptions are not plausible.</p>
<p>Finally, controlled mean comparison tables introduce the idea of holding a third variable constant. This helps distinguish additive, spurious, and interactive relationships. Controlled comparisons are useful, but they quickly become complex, which motivates later use of regression.</p>
<p>The core lesson is that comparing groups requires both statistical technique and substantive judgment. We must know how to calculate differences and standard errors, but we must also ask whether the groups are truly comparable and whether the observed differences support causal claims.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter-9.html" class="pagination-link" aria-label="Chapter 9: Experiments and Causality">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 9: Experiments and Causality</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter-11.html" class="pagination-link" aria-label="Chapter 11: Association Between Categorical Variables">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>