<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>13&nbsp; Chapter 12: ANOVA – PubPol 529: Coursebook</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./chapter-13.html" rel="next">
<link href="./chapter-11.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e944e0e12dd6c2e1651c888e836d9b4b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./chapter-12.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">PubPol 529: Coursebook</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">PubPol 529: Coursebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Chapter 1: Measurement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Chapter 2: Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Chapter 3: Descriptive Statistics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Chapter 4: Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Chapter 5: Probability Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Chapter 6: Sampling Distributions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-7.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Chapter 7: Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-8.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Chapter 8: Significance Tests</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-9.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Chapter 9: Experiments and Causality</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-10.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Chapter 10: Comparison of Two Groups</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-11.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-12.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 13: Correlation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./chapter-14.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Chapter 14: Linear Regression</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#comparing-several-means" id="toc-comparing-several-means" class="nav-link active" data-scroll-target="#comparing-several-means"><span class="header-section-number">13.1</span> Comparing Several Means</a></li>
  <li><a href="#what-does-anova-ask" id="toc-what-does-anova-ask" class="nav-link" data-scroll-target="#what-does-anova-ask"><span class="header-section-number">13.2</span> What Does ANOVA Ask?</a></li>
  <li><a href="#example-party-identification-and-obama-thermometer-scores" id="toc-example-party-identification-and-obama-thermometer-scores" class="nav-link" data-scroll-target="#example-party-identification-and-obama-thermometer-scores"><span class="header-section-number">13.3</span> Example: Party Identification and Obama Thermometer Scores</a></li>
  <li><a href="#part-i-the-logic-of-anova" id="toc-part-i-the-logic-of-anova" class="nav-link" data-scroll-target="#part-i-the-logic-of-anova"><span class="header-section-number">14</span> Part I: The Logic of ANOVA</a>
  <ul class="collapse">
  <li><a href="#analysis-of-variance" id="toc-analysis-of-variance" class="nav-link" data-scroll-target="#analysis-of-variance"><span class="header-section-number">14.1</span> Analysis of Variance</a></li>
  <li><a href="#between-group-variation" id="toc-between-group-variation" class="nav-link" data-scroll-target="#between-group-variation"><span class="header-section-number">14.2</span> Between-Group Variation</a></li>
  <li><a href="#within-group-variation" id="toc-within-group-variation" class="nav-link" data-scroll-target="#within-group-variation"><span class="header-section-number">14.3</span> Within-Group Variation</a></li>
  <li><a href="#the-f-statistic" id="toc-the-f-statistic" class="nav-link" data-scroll-target="#the-f-statistic"><span class="header-section-number">14.4</span> The F Statistic</a></li>
  <li><a href="#visual-intuition" id="toc-visual-intuition" class="nav-link" data-scroll-target="#visual-intuition"><span class="header-section-number">14.5</span> Visual Intuition</a></li>
  </ul></li>
  <li><a href="#part-ii-mathematical-details" id="toc-part-ii-mathematical-details" class="nav-link" data-scroll-target="#part-ii-mathematical-details"><span class="header-section-number">15</span> Part II: Mathematical Details</a>
  <ul class="collapse">
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation"><span class="header-section-number">15.1</span> Notation</a></li>
  <li><a href="#between-sum-of-squares" id="toc-between-sum-of-squares" class="nav-link" data-scroll-target="#between-sum-of-squares"><span class="header-section-number">15.2</span> Between Sum of Squares</a></li>
  <li><a href="#within-sum-of-squares" id="toc-within-sum-of-squares" class="nav-link" data-scroll-target="#within-sum-of-squares"><span class="header-section-number">15.3</span> Within Sum of Squares</a></li>
  <li><a href="#the-f-statistic-formula" id="toc-the-f-statistic-formula" class="nav-link" data-scroll-target="#the-f-statistic-formula"><span class="header-section-number">15.4</span> The F Statistic Formula</a></li>
  <li><a href="#interpreting-the-f-statistic" id="toc-interpreting-the-f-statistic" class="nav-link" data-scroll-target="#interpreting-the-f-statistic"><span class="header-section-number">15.5</span> Interpreting the F Statistic</a></li>
  </ul></li>
  <li><a href="#part-iii-one-way-anova-example" id="toc-part-iii-one-way-anova-example" class="nav-link" data-scroll-target="#part-iii-one-way-anova-example"><span class="header-section-number">16</span> Part III: One-Way ANOVA Example</a>
  <ul class="collapse">
  <li><a href="#obama-thermometer-scores-by-party" id="toc-obama-thermometer-scores-by-party" class="nav-link" data-scroll-target="#obama-thermometer-scores-by-party"><span class="header-section-number">16.1</span> Obama Thermometer Scores by Party</a></li>
  <li><a href="#calculating-between-group-variation" id="toc-calculating-between-group-variation" class="nav-link" data-scroll-target="#calculating-between-group-variation"><span class="header-section-number">16.2</span> Calculating Between-Group Variation</a></li>
  <li><a href="#calculating-within-group-variation" id="toc-calculating-within-group-variation" class="nav-link" data-scroll-target="#calculating-within-group-variation"><span class="header-section-number">16.3</span> Calculating Within-Group Variation</a></li>
  <li><a href="#calculating-the-f-statistic" id="toc-calculating-the-f-statistic" class="nav-link" data-scroll-target="#calculating-the-f-statistic"><span class="header-section-number">16.4</span> Calculating the F Statistic</a></li>
  <li><a href="#anova-output" id="toc-anova-output" class="nav-link" data-scroll-target="#anova-output"><span class="header-section-number">16.5</span> ANOVA Output</a></li>
  <li><a href="#r-squared-in-anova" id="toc-r-squared-in-anova" class="nav-link" data-scroll-target="#r-squared-in-anova"><span class="header-section-number">16.6</span> R-Squared in ANOVA</a></li>
  </ul></li>
  <li><a href="#part-iv-another-one-way-anova-example" id="toc-part-iv-another-one-way-anova-example" class="nav-link" data-scroll-target="#part-iv-another-one-way-anova-example"><span class="header-section-number">17</span> Part IV: Another One-Way ANOVA Example</a>
  <ul class="collapse">
  <li><a href="#test-scores-across-schools" id="toc-test-scores-across-schools" class="nav-link" data-scroll-target="#test-scores-across-schools"><span class="header-section-number">17.1</span> Test Scores Across Schools</a></li>
  </ul></li>
  <li><a href="#part-v-two-way-anova" id="toc-part-v-two-way-anova" class="nav-link" data-scroll-target="#part-v-two-way-anova"><span class="header-section-number">18</span> Part V: Two-Way ANOVA</a>
  <ul class="collapse">
  <li><a href="#adding-a-second-categorical-variable" id="toc-adding-a-second-categorical-variable" class="nav-link" data-scroll-target="#adding-a-second-categorical-variable"><span class="header-section-number">18.1</span> Adding a Second Categorical Variable</a></li>
  <li><a href="#example-party-id-region-and-obama-thermometer-scores" id="toc-example-party-id-region-and-obama-thermometer-scores" class="nav-link" data-scroll-target="#example-party-id-region-and-obama-thermometer-scores"><span class="header-section-number">18.2</span> Example: Party ID, Region, and Obama Thermometer Scores</a></li>
  <li><a href="#interpreting-two-way-anova-output" id="toc-interpreting-two-way-anova-output" class="nav-link" data-scroll-target="#interpreting-two-way-anova-output"><span class="header-section-number">18.3</span> Interpreting Two-Way ANOVA Output</a></li>
  <li><a href="#controlling-for-variables-in-anova" id="toc-controlling-for-variables-in-anova" class="nav-link" data-scroll-target="#controlling-for-variables-in-anova"><span class="header-section-number">18.4</span> Controlling for Variables in ANOVA</a></li>
  </ul></li>
  <li><a href="#part-vi-democracy-wealth-and-life-expectancy" id="toc-part-vi-democracy-wealth-and-life-expectancy" class="nav-link" data-scroll-target="#part-vi-democracy-wealth-and-life-expectancy"><span class="header-section-number">19</span> Part VI: Democracy, Wealth, and Life Expectancy</a>
  <ul class="collapse">
  <li><a href="#the-research-question" id="toc-the-research-question" class="nav-link" data-scroll-target="#the-research-question"><span class="header-section-number">19.1</span> The Research Question</a></li>
  <li><a href="#mean-comparison-table" id="toc-mean-comparison-table" class="nav-link" data-scroll-target="#mean-comparison-table"><span class="header-section-number">19.2</span> Mean Comparison Table</a></li>
  <li><a href="#two-way-anova-interpretation" id="toc-two-way-anova-interpretation" class="nav-link" data-scroll-target="#two-way-anova-interpretation"><span class="header-section-number">19.3</span> Two-Way ANOVA Interpretation</a></li>
  </ul></li>
  <li><a href="#part-vii-anova-and-regression" id="toc-part-vii-anova-and-regression" class="nav-link" data-scroll-target="#part-vii-anova-and-regression"><span class="header-section-number">20</span> Part VII: ANOVA and Regression</a>
  <ul class="collapse">
  <li><a href="#anova-as-a-special-case-of-regression" id="toc-anova-as-a-special-case-of-regression" class="nav-link" data-scroll-target="#anova-as-a-special-case-of-regression"><span class="header-section-number">20.1</span> ANOVA as a Special Case of Regression</a></li>
  <li><a href="#when-is-anova-useful" id="toc-when-is-anova-useful" class="nav-link" data-scroll-target="#when-is-anova-useful"><span class="header-section-number">20.2</span> When Is ANOVA Useful?</a></li>
  </ul></li>
  <li><a href="#part-viii-interpreting-anova-carefully" id="toc-part-viii-interpreting-anova-carefully" class="nav-link" data-scroll-target="#part-viii-interpreting-anova-carefully"><span class="header-section-number">21</span> Part VIII: Interpreting ANOVA Carefully</a>
  <ul class="collapse">
  <li><a href="#anova-tells-us-whether-means-differ" id="toc-anova-tells-us-whether-means-differ" class="nav-link" data-scroll-target="#anova-tells-us-whether-means-differ"><span class="header-section-number">21.1</span> ANOVA Tells Us Whether Means Differ</a></li>
  <li><a href="#statistical-versus-substantive-significance" id="toc-statistical-versus-substantive-significance" class="nav-link" data-scroll-target="#statistical-versus-substantive-significance"><span class="header-section-number">21.2</span> Statistical Versus Substantive Significance</a></li>
  <li><a href="#causality" id="toc-causality" class="nav-link" data-scroll-target="#causality"><span class="header-section-number">21.3</span> Causality</a></li>
  </ul></li>
  <li><a href="#key-terms" id="toc-key-terms" class="nav-link" data-scroll-target="#key-terms"><span class="header-section-number">22</span> Key Terms</a></li>
  <li><a href="#chapter-summary" id="toc-chapter-summary" class="nav-link" data-scroll-target="#chapter-summary"><span class="header-section-number">23</span> Chapter Summary</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Chapter 12: ANOVA</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>We now turn to a method called <strong>ANOVA</strong>, which stands for <strong>analysis of variance</strong>.</p>
<p>ANOVA is used when we want to compare more than two means at the same time. If we have only two means, we can use a difference-of-means t-test. But if we have three, four, five, or more group means, running many separate t-tests becomes cumbersome and can create problems with repeated testing.</p>
<p>ANOVA gives us a way to ask one broader question:</p>
<blockquote class="blockquote">
<p>Are the means across these groups all the same, or does at least one group differ?</p>
</blockquote>
<p>ANOVA is not as widely used in some areas of modern applied statistics as regression, because regression can accomplish many of the same goals more flexibly. Still, ANOVA remains useful conceptually and practically. It helps us understand how variation in an outcome can be partitioned into variation explained by group differences and variation left unexplained within groups.</p>
<p>The central idea is this:</p>
<blockquote class="blockquote">
<p>ANOVA compares variation between groups to variation within groups.</p>
</blockquote>
<p>If between-group variation is large relative to within-group variation, then group membership helps explain the outcome. If between-group variation is small relative to within-group variation, then the group categories do not explain much.</p>
<hr>
<section id="comparing-several-means" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="comparing-several-means"><span class="header-section-number">13.1</span> Comparing Several Means</h2>
<p>Suppose we have an interval-level dependent variable <span class="math inline">\(Y\)</span>, such as:</p>
<ul>
<li>test score</li>
<li>income</li>
<li>life expectancy</li>
<li>thermometer rating</li>
<li>infant mortality rate</li>
<li>air quality index</li>
</ul>
<p>And suppose we have a categorical independent variable <span class="math inline">\(X\)</span>, such as:</p>
<ul>
<li>political party</li>
<li>school</li>
<li>classroom</li>
<li>region</li>
<li>regime type</li>
<li>treatment category</li>
</ul>
<p>If <span class="math inline">\(X\)</span> has only two categories, we can compare the two means using a t-test.</p>
<p>But if <span class="math inline">\(X\)</span> has more than two categories, we need another approach.</p>
<p>For example, suppose we want to compare student test scores across five classrooms. The null hypothesis is that all five classrooms have the same mean test score. The alternative is that at least one classroom has a different mean.</p>
<p>This is precisely the kind of question ANOVA is designed to answer.</p>
<hr>
</section>
<section id="what-does-anova-ask" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="what-does-anova-ask"><span class="header-section-number">13.2</span> What Does ANOVA Ask?</h2>
<p>ANOVA asks whether the means of an interval-level variable differ across categories of one or more categorical variables.</p>
<p>For a one-way ANOVA, we have:</p>
<ul>
<li>one interval-level dependent variable, <span class="math inline">\(Y\)</span></li>
<li>one categorical independent variable, <span class="math inline">\(X\)</span></li>
</ul>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2 = \mu_3 = \cdots = \mu_G
\]</span></p>
<p>where <span class="math inline">\(G\)</span> is the number of groups.</p>
<p>The alternative hypothesis is:</p>
<p><span class="math display">\[
H_A: \text{At least one group mean differs from the others.}
\]</span></p>
<p>Notice that the alternative hypothesis does not say exactly which group differs. It only says that not all group means are equal.</p>
<p>If ANOVA rejects the null hypothesis, we know that at least one group mean differs, but we may need additional analysis to determine which specific groups differ from one another.</p>
<hr>
</section>
<section id="example-party-identification-and-obama-thermometer-scores" class="level2" data-number="13.3">
<h2 data-number="13.3" class="anchored" data-anchor-id="example-party-identification-and-obama-thermometer-scores"><span class="header-section-number">13.3</span> Example: Party Identification and Obama Thermometer Scores</h2>
<p>Suppose respondents are asked to rate Barack Obama on a feeling thermometer from 0 to 100.</p>
<ul>
<li>0 means very cold feelings.</li>
<li>100 means very warm feelings.</li>
</ul>
<p>The overall mean thermometer score is:</p>
<p><span class="math display">\[
\bar{Y} = 60.72
\]</span></p>
<p>Now suppose we compare mean thermometer scores across party identification:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Party ID</th>
<th style="text-align: right;">Mean Obama Thermometer Score</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Democrat</td>
<td style="text-align: right;">85.31</td>
<td style="text-align: right;">19.10</td>
<td style="text-align: right;">2,197</td>
</tr>
<tr class="even">
<td>Independent</td>
<td style="text-align: right;">55.70</td>
<td style="text-align: right;">27.10</td>
<td style="text-align: right;">1,776</td>
</tr>
<tr class="odd">
<td>Republican</td>
<td style="text-align: right;">26.62</td>
<td style="text-align: right;">25.40</td>
<td style="text-align: right;">1,501</td>
</tr>
<tr class="even">
<td><strong>Overall</strong></td>
<td style="text-align: right;"><strong>60.72</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>5,474</strong></td>
</tr>
</tbody>
</table>
<p>The means clearly differ.</p>
<p>Democrats rate Obama much more warmly than Republicans do, with independents in the middle.</p>
<p>The question is not whether the sample means differ. They plainly do. The question is whether those differences are large enough, relative to the variation within groups, to reject the null hypothesis that the population means are all the same.</p>
<hr>
</section>
<section id="part-i-the-logic-of-anova" class="level1" data-number="14">
<h1 data-number="14"><span class="header-section-number">14</span> Part I: The Logic of ANOVA</h1>
<section id="analysis-of-variance" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="analysis-of-variance"><span class="header-section-number">14.1</span> Analysis of Variance</h2>
<p>ANOVA stands for <strong>analysis of variance</strong>.</p>
<p>That name may seem surprising because we are comparing means. But the method works by analyzing variance.</p>
<p>Specifically, ANOVA partitions the total variation in <span class="math inline">\(Y\)</span> into two parts:</p>
<ol type="1">
<li><strong>Between-group variation</strong></li>
<li><strong>Within-group variation</strong></li>
</ol>
<p>The key question is:</p>
<blockquote class="blockquote">
<p>Is variation between group means large relative to variation within groups?</p>
</blockquote>
<p>If the group means are far apart and individuals within each group are clustered close to their group mean, then group membership explains a lot of variation in <span class="math inline">\(Y\)</span>.</p>
<p>If the group means are close together or the groups overlap heavily, then group membership does not explain much variation in <span class="math inline">\(Y\)</span>.</p>
<hr>
</section>
<section id="between-group-variation" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="between-group-variation"><span class="header-section-number">14.2</span> Between-Group Variation</h2>
<p><strong>Between-group variation</strong> refers to variation in the group means.</p>
<p>In the Obama thermometer example, the group means are:</p>
<ul>
<li>Democrats: 85.31</li>
<li>Independents: 55.70</li>
<li>Republicans: 26.62</li>
</ul>
<p>These means are far apart.</p>
<p>That suggests party identification explains a substantial amount of variation in Obama thermometer scores.</p>
<p>Between-group variation asks:</p>
<blockquote class="blockquote">
<p>How far are the group means from the overall mean?</p>
</blockquote>
<p>The overall mean is:</p>
<p><span class="math display">\[
\bar{Y} = 60.72
\]</span></p>
<p>So we examine how far each group mean is from 60.72, weighting by group size.</p>
<hr>
</section>
<section id="within-group-variation" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="within-group-variation"><span class="header-section-number">14.3</span> Within-Group Variation</h2>
<p><strong>Within-group variation</strong> refers to variation among individuals inside the same group.</p>
<p>Not all Democrats rate Obama exactly the same way. Not all Republicans do either. There is variation within each party category.</p>
<p>For Democrats, the standard deviation is 19.10.<br>
For Independents, it is 27.10.<br>
For Republicans, it is 25.40.</p>
<p>Within-group variation asks:</p>
<blockquote class="blockquote">
<p>How much do individuals vary around their own group means?</p>
</blockquote>
<p>If within-group variation is large, then group membership may not explain much. If within-group variation is small, and group means are far apart, then group membership explains more.</p>
<hr>
</section>
<section id="the-f-statistic" class="level2" data-number="14.4">
<h2 data-number="14.4" class="anchored" data-anchor-id="the-f-statistic"><span class="header-section-number">14.4</span> The F Statistic</h2>
<p>ANOVA uses an <strong>F statistic</strong>.</p>
<p>The F statistic is a ratio:</p>
<p><span class="math display">\[
F =
\frac{\text{Between-group variance}}
{\text{Within-group variance}}
\]</span></p>
<p>If between-group variance is large relative to within-group variance, <span class="math inline">\(F\)</span> will be large.</p>
<p>If between-group variance is small relative to within-group variance, <span class="math inline">\(F\)</span> will be small.</p>
<p>The smallest possible F statistic is 0. That would occur when all group means are identical.</p>
<p>Because variances are always nonnegative, F statistics cannot be negative.</p>
<p>Like chi-square tests, ANOVA uses a one-sided test. We reject the null hypothesis only for large values of <span class="math inline">\(F\)</span>.</p>
<hr>
</section>
<section id="visual-intuition" class="level2" data-number="14.5">
<h2 data-number="14.5" class="anchored" data-anchor-id="visual-intuition"><span class="header-section-number">14.5</span> Visual Intuition</h2>
<p>Imagine three groups.</p>
<p>In one scenario, each group is tightly clustered around a different mean. The group distributions barely overlap. Between-group variation is large, and within-group variation is small. ANOVA will produce a large F statistic.</p>
<p>In another scenario, the three group means differ slightly, but the observations within each group are widely spread out. The distributions overlap heavily. Between-group variation is small relative to within-group variation. ANOVA will produce a smaller F statistic.</p>
<p>The F statistic formalizes this comparison:</p>
<p><span class="math display">\[
\text{Are group means far apart compared to the variation inside the groups?}
\]</span></p>
<hr>
</section>
</section>
<section id="part-ii-mathematical-details" class="level1" data-number="15">
<h1 data-number="15"><span class="header-section-number">15</span> Part II: Mathematical Details</h1>
<section id="notation" class="level2" data-number="15.1">
<h2 data-number="15.1" class="anchored" data-anchor-id="notation"><span class="header-section-number">15.1</span> Notation</h2>
<p>Suppose we have:</p>
<ul>
<li>total sample size <span class="math inline">\(N\)</span></li>
<li>number of groups <span class="math inline">\(G\)</span></li>
<li>sample size in group <span class="math inline">\(g\)</span>: <span class="math inline">\(n_g\)</span></li>
<li>outcome for person <span class="math inline">\(i\)</span> in group <span class="math inline">\(g\)</span>: <span class="math inline">\(Y_{ig}\)</span></li>
<li>mean of group <span class="math inline">\(g\)</span>: <span class="math inline">\(\bar{Y}_g\)</span></li>
<li>overall mean: <span class="math inline">\(\bar{Y}\)</span></li>
</ul>
<p>ANOVA compares the group means <span class="math inline">\(\bar{Y}_g\)</span> to the overall mean <span class="math inline">\(\bar{Y}\)</span>, while also accounting for variation among individuals within each group.</p>
<hr>
</section>
<section id="between-sum-of-squares" class="level2" data-number="15.2">
<h2 data-number="15.2" class="anchored" data-anchor-id="between-sum-of-squares"><span class="header-section-number">15.2</span> Between Sum of Squares</h2>
<p>The <strong>between sum of squares</strong> measures how far group means are from the overall mean, weighted by group size.</p>
<p><span class="math display">\[
SS_{between}
=
\sum_{g=1}^{G}
n_g(\bar{Y}_g - \bar{Y})^2
\]</span></p>
<p>For each group:</p>
<ol type="1">
<li>Take the group mean.</li>
<li>Subtract the overall mean.</li>
<li>Square the difference.</li>
<li>Multiply by the group size.</li>
<li>Add across groups.</li>
</ol>
<p>Groups with more cases contribute more to the between-group sum of squares.</p>
<p>The degrees of freedom for the between-group component are:</p>
<p><span class="math display">\[
df_{between} = G - 1
\]</span></p>
<p>The <strong>between-group variance</strong>, also called the <strong>mean square between</strong>, is:</p>
<p><span class="math display">\[
MS_{between}
=
\frac{SS_{between}}{G-1}
\]</span></p>
<hr>
</section>
<section id="within-sum-of-squares" class="level2" data-number="15.3">
<h2 data-number="15.3" class="anchored" data-anchor-id="within-sum-of-squares"><span class="header-section-number">15.3</span> Within Sum of Squares</h2>
<p>The <strong>within sum of squares</strong> measures variation of individuals around their own group means.</p>
<p><span class="math display">\[
SS_{within}
=
\sum_{g=1}^{G}
\sum_{i=1}^{n_g}
(Y_{ig} - \bar{Y}_g)^2
\]</span></p>
<p>This is the sum of the within-group sums of squares.</p>
<p>Another way to calculate it is:</p>
<p><span class="math display">\[
SS_{within}
=
\sum_{g=1}^{G}
(n_g-1)s_g^2
\]</span></p>
<p>where <span class="math inline">\(s_g^2\)</span> is the sample variance within group <span class="math inline">\(g\)</span>.</p>
<p>This second formula is often more convenient if we already know group standard deviations.</p>
<p>The degrees of freedom for the within-group component are:</p>
<p><span class="math display">\[
df_{within} = N - G
\]</span></p>
<p>The <strong>within-group variance</strong>, also called the <strong>mean square within</strong>, is:</p>
<p><span class="math display">\[
MS_{within}
=
\frac{SS_{within}}{N-G}
\]</span></p>
<hr>
</section>
<section id="the-f-statistic-formula" class="level2" data-number="15.4">
<h2 data-number="15.4" class="anchored" data-anchor-id="the-f-statistic-formula"><span class="header-section-number">15.4</span> The F Statistic Formula</h2>
<p>The F statistic is:</p>
<p><span class="math display">\[
F =
\frac{MS_{between}}{MS_{within}}
\]</span></p>
<p>or:</p>
<p><span class="math display">\[
F =
\frac{SS_{between}/(G-1)}
{SS_{within}/(N-G)}
\]</span></p>
<p>The F statistic has two degrees of freedom:</p>
<p><span class="math display">\[
F_{G-1,\;N-G}
\]</span></p>
<p>The first is the numerator degrees of freedom.</p>
<p>The second is the denominator degrees of freedom.</p>
<p>Software will report both.</p>
<hr>
</section>
<section id="interpreting-the-f-statistic" class="level2" data-number="15.5">
<h2 data-number="15.5" class="anchored" data-anchor-id="interpreting-the-f-statistic"><span class="header-section-number">15.5</span> Interpreting the F Statistic</h2>
<p>A large F statistic means that group means are far apart relative to within-group variation.</p>
<p>A small F statistic means that group means are not far apart relative to within-group variation.</p>
<p>The F test evaluates:</p>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2 = \cdots = \mu_G
\]</span></p>
<p>against:</p>
<p><span class="math display">\[
H_A: \text{At least one group mean differs.}
\]</span></p>
<p>If the p-value associated with F is less than alpha, we reject the null hypothesis.</p>
<hr>
</section>
</section>
<section id="part-iii-one-way-anova-example" class="level1" data-number="16">
<h1 data-number="16"><span class="header-section-number">16</span> Part III: One-Way ANOVA Example</h1>
<section id="obama-thermometer-scores-by-party" class="level2" data-number="16.1">
<h2 data-number="16.1" class="anchored" data-anchor-id="obama-thermometer-scores-by-party"><span class="header-section-number">16.1</span> Obama Thermometer Scores by Party</h2>
<p>Return to the Obama thermometer example.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Party ID</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">Standard Deviation</th>
<th style="text-align: right;">Sample Size</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Democrat</td>
<td style="text-align: right;">85.31</td>
<td style="text-align: right;">19.10</td>
<td style="text-align: right;">2,197</td>
</tr>
<tr class="even">
<td>Independent</td>
<td style="text-align: right;">55.70</td>
<td style="text-align: right;">27.10</td>
<td style="text-align: right;">1,776</td>
</tr>
<tr class="odd">
<td>Republican</td>
<td style="text-align: right;">26.62</td>
<td style="text-align: right;">25.40</td>
<td style="text-align: right;">1,501</td>
</tr>
<tr class="even">
<td><strong>Overall</strong></td>
<td style="text-align: right;"><strong>60.72</strong></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"><strong>5,474</strong></td>
</tr>
</tbody>
</table>
<p>There are:</p>
<p><span class="math display">\[
G = 3
\]</span></p>
<p>groups and:</p>
<p><span class="math display">\[
N = 5474
\]</span></p>
<p>observations.</p>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \mu_D = \mu_I = \mu_R
\]</span></p>
<p>The alternative is:</p>
<p><span class="math display">\[
H_A: \text{At least one party mean differs.}
\]</span></p>
<hr>
</section>
<section id="calculating-between-group-variation" class="level2" data-number="16.2">
<h2 data-number="16.2" class="anchored" data-anchor-id="calculating-between-group-variation"><span class="header-section-number">16.2</span> Calculating Between-Group Variation</h2>
<p>The between sum of squares is:</p>
<p><span class="math display">\[
SS_{between}
=
\sum_{g=1}^{G}
n_g(\bar{Y}_g - \bar{Y})^2
\]</span></p>
<p>Substitute values:</p>
<p><span class="math display">\[
SS_{between}
=
2197(85.31 - 60.72)^2
+
1776(55.70 - 60.72)^2
+
1501(26.62 - 60.72)^2
\]</span></p>
<p>This gives approximately:</p>
<p><span class="math display">\[
SS_{between} = 2{,}881{,}370.9
\]</span></p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df_{between} = G - 1 = 3 - 1 = 2
\]</span></p>
<p>So:</p>
<p><span class="math display">\[
MS_{between}
=
\frac{2{,}881{,}370.9}{2}
\]</span></p>
<p><span class="math display">\[
MS_{between}
=
1{,}440{,}685.45
\]</span></p>
<hr>
</section>
<section id="calculating-within-group-variation" class="level2" data-number="16.3">
<h2 data-number="16.3" class="anchored" data-anchor-id="calculating-within-group-variation"><span class="header-section-number">16.3</span> Calculating Within-Group Variation</h2>
<p>Using group standard deviations:</p>
<p><span class="math display">\[
SS_{within}
=
\sum_{g=1}^{G}
(n_g-1)s_g^2
\]</span></p>
<p>Substitute values:</p>
<p><span class="math display">\[
SS_{within}
=
(2197-1)(19.10)^2
+
(1776-1)(27.10)^2
+
(1501-1)(25.40)^2
\]</span></p>
<p>This gives approximately:</p>
<p><span class="math display">\[
SS_{within} = 3{,}689{,}000
\]</span></p>
<p>Degrees of freedom:</p>
<p><span class="math display">\[
df_{within} = N - G = 5474 - 3 = 5471
\]</span></p>
<p>So:</p>
<p><span class="math display">\[
MS_{within}
=
\frac{3{,}689{,}000}{5471}
\]</span></p>
<p><span class="math display">\[
MS_{within}
\approx 674.4
\]</span></p>
<hr>
</section>
<section id="calculating-the-f-statistic" class="level2" data-number="16.4">
<h2 data-number="16.4" class="anchored" data-anchor-id="calculating-the-f-statistic"><span class="header-section-number">16.4</span> Calculating the F Statistic</h2>
<p>Now calculate:</p>
<p><span class="math display">\[
F =
\frac{MS_{between}}{MS_{within}}
\]</span></p>
<p><span class="math display">\[
F =
\frac{1{,}440{,}685.45}{674.4}
\]</span></p>
<p><span class="math display">\[
F \approx 2136
\]</span></p>
<p>This is extremely large.</p>
<p>The p-value is effectively zero.</p>
<p>Therefore, we reject the null hypothesis that Democrats, Independents, and Republicans all have the same mean Obama thermometer score.</p>
<p>Party identification explains a substantial amount of variation in Obama thermometer ratings.</p>
<p>Not exactly a plot twist worthy of prestige television, but statistically speaking, it is very clear.</p>
<hr>
</section>
<section id="anova-output" class="level2" data-number="16.5">
<h2 data-number="16.5" class="anchored" data-anchor-id="anova-output"><span class="header-section-number">16.5</span> ANOVA Output</h2>
<p>Statistical software usually reports an ANOVA table with columns such as:</p>
<ul>
<li>source</li>
<li>sum of squares</li>
<li>degrees of freedom</li>
<li>mean square</li>
<li>F statistic</li>
<li>p-value</li>
</ul>
<p>For the Obama thermometer example, the table conceptually looks like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">Sum of Squares</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">Mean Square</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Party ID</td>
<td style="text-align: right;">2,881,371</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1,440,685</td>
<td style="text-align: right;">2136</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td>Residual</td>
<td style="text-align: right;">3,689,000</td>
<td style="text-align: right;">5,471</td>
<td style="text-align: right;">674</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td style="text-align: right;">6,570,371</td>
<td style="text-align: right;">5,473</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>The row for Party ID represents between-group variation.</p>
<p>The residual row represents within-group variation.</p>
<p>The F statistic is:</p>
<p><span class="math display">\[
\frac{\text{Mean Square for Party ID}}
{\text{Mean Square Residual}}
\]</span></p>
<p>The p-value tells us whether the group means differ with statistical significance.</p>
<hr>
</section>
<section id="r-squared-in-anova" class="level2" data-number="16.6">
<h2 data-number="16.6" class="anchored" data-anchor-id="r-squared-in-anova"><span class="header-section-number">16.6</span> R-Squared in ANOVA</h2>
<p>Software may also report <span class="math inline">\(R^2\)</span>.</p>
<p>In ANOVA, <span class="math inline">\(R^2\)</span> represents the proportion of total variation in <span class="math inline">\(Y\)</span> explained by the group categories.</p>
<p><span class="math display">\[
R^2 =
\frac{SS_{between}}{SS_{total}}
\]</span></p>
<p>In the Obama thermometer example, party ID explains roughly 44 percent of the variation in Obama thermometer scores.</p>
<p>That is a large amount of explained variation for social science data.</p>
<p>We will return to <span class="math inline">\(R^2\)</span> in more detail when discussing regression.</p>
<hr>
</section>
</section>
<section id="part-iv-another-one-way-anova-example" class="level1" data-number="17">
<h1 data-number="17"><span class="header-section-number">17</span> Part IV: Another One-Way ANOVA Example</h1>
<section id="test-scores-across-schools" class="level2" data-number="17.1">
<h2 data-number="17.1" class="anchored" data-anchor-id="test-scores-across-schools"><span class="header-section-number">17.1</span> Test Scores Across Schools</h2>
<p>Suppose we have math test scores for students in an urban school district.</p>
<p>There are:</p>
<ul>
<li>8,064 students</li>
<li>25 schools</li>
</ul>
<p>The question is:</p>
<blockquote class="blockquote">
<p>Do mean math test scores differ across schools?</p>
</blockquote>
<p>The null hypothesis is:</p>
<p><span class="math display">\[
H_0: \mu_1 = \mu_2 = \cdots = \mu_{25}
\]</span></p>
<p>The alternative is:</p>
<p><span class="math display">\[
H_A: \text{At least one school mean differs.}
\]</span></p>
<p>A one-way ANOVA can test whether school membership explains statistically significant variation in test scores.</p>
<p>If the F statistic is large and the p-value is small, we reject the null hypothesis and conclude that mean test scores differ across schools.</p>
<p>This does not tell us why schools differ. Differences may reflect school quality, neighborhood inequality, student composition, resources, peer effects, or other factors. ANOVA tells us whether there are differences, not what caused them.</p>
<hr>
</section>
</section>
<section id="part-v-two-way-anova" class="level1" data-number="18">
<h1 data-number="18"><span class="header-section-number">18</span> Part V: Two-Way ANOVA</h1>
<section id="adding-a-second-categorical-variable" class="level2" data-number="18.1">
<h2 data-number="18.1" class="anchored" data-anchor-id="adding-a-second-categorical-variable"><span class="header-section-number">18.1</span> Adding a Second Categorical Variable</h2>
<p>A <strong>two-way ANOVA</strong> uses two categorical independent variables to explain variation in an interval-level dependent variable.</p>
<p>For example, suppose we want to explain Obama thermometer scores using:</p>
<ul>
<li>party identification</li>
<li>region</li>
</ul>
<p>Party ID has three categories:</p>
<ul>
<li>Democrat</li>
<li>Independent</li>
<li>Republican</li>
</ul>
<p>Region has two categories:</p>
<ul>
<li>South</li>
<li>not South</li>
</ul>
<p>Together, they create six combinations:</p>
<ol type="1">
<li>Democrat, not South</li>
<li>Democrat, South</li>
<li>Independent, not South</li>
<li>Independent, South</li>
<li>Republican, not South</li>
<li>Republican, South</li>
</ol>
<p>Two-way ANOVA allows us to ask whether party matters after controlling for region, and whether region matters after controlling for party.</p>
<hr>
</section>
<section id="example-party-id-region-and-obama-thermometer-scores" class="level2" data-number="18.2">
<h2 data-number="18.2" class="anchored" data-anchor-id="example-party-id-region-and-obama-thermometer-scores"><span class="header-section-number">18.2</span> Example: Party ID, Region, and Obama Thermometer Scores</h2>
<p>Suppose the table looks roughly like this:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Party ID</th>
<th style="text-align: right;">Not South Mean</th>
<th style="text-align: right;">South Mean</th>
<th style="text-align: right;">Overall Mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Democrat</td>
<td style="text-align: right;">82.0</td>
<td style="text-align: right;">86.2</td>
<td style="text-align: right;">85.3</td>
</tr>
<tr class="even">
<td>Independent</td>
<td style="text-align: right;">54.2</td>
<td style="text-align: right;">51.5</td>
<td style="text-align: right;">55.7</td>
</tr>
<tr class="odd">
<td>Republican</td>
<td style="text-align: right;">27.1</td>
<td style="text-align: right;">24.7</td>
<td style="text-align: right;">26.6</td>
</tr>
</tbody>
</table>
<p>We can ask several questions.</p>
<p>First:</p>
<blockquote class="blockquote">
<p>Do all six means differ from one another?</p>
</blockquote>
<p>That is the model-level question.</p>
<p>Second:</p>
<blockquote class="blockquote">
<p>After controlling for region, does party ID still explain differences in Obama thermometer scores?</p>
</blockquote>
<p>Third:</p>
<blockquote class="blockquote">
<p>After controlling for party ID, does region still explain differences in Obama thermometer scores?</p>
</blockquote>
<p>ANOVA can provide F tests for each question.</p>
<hr>
</section>
<section id="interpreting-two-way-anova-output" class="level2" data-number="18.3">
<h2 data-number="18.3" class="anchored" data-anchor-id="interpreting-two-way-anova-output"><span class="header-section-number">18.3</span> Interpreting Two-Way ANOVA Output</h2>
<p>A two-way ANOVA output may include rows such as:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td style="text-align: right;">large</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td>Party ID</td>
<td style="text-align: right;">very large</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td>Region</td>
<td style="text-align: right;">smaller</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="even">
<td>Residual</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tbody>
</table>
<p>The <strong>model</strong> row tests whether the full set of categories, taken together, explains variation in <span class="math inline">\(Y\)</span>.</p>
<p>The <strong>Party ID</strong> row tests whether party ID explains variation in <span class="math inline">\(Y\)</span>, after controlling for region.</p>
<p>The <strong>Region</strong> row tests whether region explains variation in <span class="math inline">\(Y\)</span>, after controlling for party ID.</p>
<p>If party ID has a very small p-value, then party ID matters even after controlling for region.</p>
<p>If region has a p-value of 0.04, then region is statistically significant at the 0.05 level, but we still need to ask whether the effect is substantively meaningful.</p>
<p>In the example, regional differences are small compared to party differences. With a large sample, even small differences may become statistically significant.</p>
<p>Statistical significance and substantive importance are not the same thing.</p>
<hr>
</section>
<section id="controlling-for-variables-in-anova" class="level2" data-number="18.4">
<h2 data-number="18.4" class="anchored" data-anchor-id="controlling-for-variables-in-anova"><span class="header-section-number">18.4</span> Controlling for Variables in ANOVA</h2>
<p>Two-way ANOVA introduces the idea of statistical control.</p>
<p>When we say:</p>
<blockquote class="blockquote">
<p>Party ID matters after controlling for region,</p>
</blockquote>
<p>we mean that differences across party categories remain even when we compare people within the same region category.</p>
<p>Likewise:</p>
<blockquote class="blockquote">
<p>Region matters after controlling for party ID</p>
</blockquote>
<p>means that regional differences remain even when we compare people within the same party category.</p>
<p>This is conceptually similar to controlled mean comparison tables. ANOVA gives us a formal significance test for those comparisons.</p>
<hr>
</section>
</section>
<section id="part-vi-democracy-wealth-and-life-expectancy" class="level1" data-number="19">
<h1 data-number="19"><span class="header-section-number">19</span> Part VI: Democracy, Wealth, and Life Expectancy</h1>
<section id="the-research-question" class="level2" data-number="19.1">
<h2 data-number="19.1" class="anchored" data-anchor-id="the-research-question"><span class="header-section-number">19.1</span> The Research Question</h2>
<p>Suppose we are interested in whether democracies have higher life expectancy than non-democracies.</p>
<p>The dependent variable is:</p>
<ul>
<li>life expectancy</li>
</ul>
<p>The categorical independent variables are:</p>
<ul>
<li>regime type: democracy or non-democracy</li>
<li>GDP per capita category: low, middle, high</li>
</ul>
<p>We know that democracies tend to be wealthier than non-democracies. Wealthier countries tend to have better health systems, infrastructure, nutrition, education, and public services.</p>
<p>So GDP per capita may confound the relationship between democracy and life expectancy.</p>
<p>A two-way ANOVA can help us ask:</p>
<ol type="1">
<li>Does regime type explain life expectancy after controlling for GDP category?</li>
<li>Does GDP category explain life expectancy after controlling for regime type?</li>
</ol>
<hr>
</section>
<section id="mean-comparison-table" class="level2" data-number="19.2">
<h2 data-number="19.2" class="anchored" data-anchor-id="mean-comparison-table"><span class="header-section-number">19.2</span> Mean Comparison Table</h2>
<p>Suppose the table is:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Regime Type</th>
<th style="text-align: right;">Low GDP</th>
<th style="text-align: right;">Middle GDP</th>
<th style="text-align: right;">High GDP</th>
<th style="text-align: right;">Overall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Non-democracy</td>
<td style="text-align: right;">57.8</td>
<td style="text-align: right;">68.7</td>
<td style="text-align: right;">73.5</td>
<td style="text-align: right;">64.5</td>
</tr>
<tr class="even">
<td>Democracy</td>
<td style="text-align: right;">63.3</td>
<td style="text-align: right;">74.1</td>
<td style="text-align: right;">79.2</td>
<td style="text-align: right;">72.5</td>
</tr>
</tbody>
</table>
<p>The table suggests that democracies have higher life expectancy within each income category.</p>
<p>It also suggests that higher-income countries have higher life expectancy within both regime categories.</p>
<p>A two-way ANOVA allows us to attach statistical significance to these patterns.</p>
<hr>
</section>
<section id="two-way-anova-interpretation" class="level2" data-number="19.3">
<h2 data-number="19.3" class="anchored" data-anchor-id="two-way-anova-interpretation"><span class="header-section-number">19.3</span> Two-Way ANOVA Interpretation</h2>
<p>Suppose ANOVA output shows:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Source</th>
<th style="text-align: right;">F</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Model</td>
<td style="text-align: right;">62.32</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="even">
<td>Democracy</td>
<td style="text-align: right;">21.81</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
<tr class="odd">
<td>GDP category</td>
<td style="text-align: right;">65.33</td>
<td style="text-align: right;">&lt;0.001</td>
</tr>
</tbody>
</table>
<p>The model as a whole is statistically significant.</p>
<p>Democracy remains statistically significant after controlling for GDP per capita category.</p>
<p>GDP per capita category remains statistically significant after controlling for democracy.</p>
<p>A careful interpretation is:</p>
<blockquote class="blockquote">
<p>We reject the null hypothesis that mean life expectancy is the same in democracies and non-democracies after controlling for GDP per capita category. We also reject the null hypothesis that mean life expectancy is the same across GDP categories after controlling for regime type.</p>
</blockquote>
<p>This does not automatically prove that democracy causes higher life expectancy. It shows that the association remains after controlling for a coarse measure of country wealth.</p>
<p>Causality would require stronger design or additional controls.</p>
<hr>
</section>
</section>
<section id="part-vii-anova-and-regression" class="level1" data-number="20">
<h1 data-number="20"><span class="header-section-number">20</span> Part VII: ANOVA and Regression</h1>
<section id="anova-as-a-special-case-of-regression" class="level2" data-number="20.1">
<h2 data-number="20.1" class="anchored" data-anchor-id="anova-as-a-special-case-of-regression"><span class="header-section-number">20.1</span> ANOVA as a Special Case of Regression</h2>
<p>ANOVA can be understood as a special case of regression with categorical independent variables.</p>
<p>In regression, categorical variables can be represented using dummy variables. A regression model with categorical predictors can reproduce ANOVA results.</p>
<p>Regression is more flexible because it can include:</p>
<ul>
<li>categorical variables</li>
<li>interval-level variables</li>
<li>multiple controls</li>
<li>interactions</li>
<li>nonlinear terms</li>
<li>complex model structures</li>
</ul>
<p>For this reason, many applied researchers use regression rather than ANOVA.</p>
<p>Still, ANOVA is conceptually useful because it teaches us how variation in an outcome can be partitioned into explained and unexplained components.</p>
<hr>
</section>
<section id="when-is-anova-useful" class="level2" data-number="20.2">
<h2 data-number="20.2" class="anchored" data-anchor-id="when-is-anova-useful"><span class="header-section-number">20.2</span> When Is ANOVA Useful?</h2>
<p>ANOVA is useful when:</p>
<ul>
<li>the dependent variable is interval-level</li>
<li>the independent variable or variables are categorical</li>
<li>we want to test whether group means differ</li>
<li>we have more than two group means</li>
<li>we want a broad test of whether categories explain variation in an outcome</li>
</ul>
<p>Examples:</p>
<ul>
<li>comparing test scores across schools</li>
<li>comparing outcomes across multiple treatment arms</li>
<li>comparing attitudes across party categories</li>
<li>comparing health outcomes across income groups</li>
<li>testing whether several group means are equal</li>
</ul>
<p>ANOVA is less useful when:</p>
<ul>
<li>we need to control for many variables</li>
<li>variables are continuous</li>
<li>the model requires more flexible specification</li>
<li>we care about estimating specific effect sizes</li>
<li>causal inference requires more advanced design</li>
</ul>
<p>In those cases, regression is usually preferable.</p>
<hr>
</section>
</section>
<section id="part-viii-interpreting-anova-carefully" class="level1" data-number="21">
<h1 data-number="21"><span class="header-section-number">21</span> Part VIII: Interpreting ANOVA Carefully</h1>
<section id="anova-tells-us-whether-means-differ" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="anova-tells-us-whether-means-differ"><span class="header-section-number">21.1</span> ANOVA Tells Us Whether Means Differ</h2>
<p>ANOVA tells us whether at least one group mean differs from the others.</p>
<p>It does not automatically tell us:</p>
<ul>
<li>which groups differ</li>
<li>how large the differences are</li>
<li>whether the differences are substantively important</li>
<li>whether the relationship is causal</li>
</ul>
<p>If ANOVA rejects the null hypothesis, researchers may conduct follow-up comparisons to determine which group means differ. These are sometimes called post-hoc tests.</p>
<hr>
</section>
<section id="statistical-versus-substantive-significance" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="statistical-versus-substantive-significance"><span class="header-section-number">21.2</span> Statistical Versus Substantive Significance</h2>
<p>As always, statistical significance is not the same as substantive importance.</p>
<p>With a very large sample, small differences in means may produce a statistically significant F statistic.</p>
<p>For example, regional differences in Obama thermometer scores may be statistically significant because the sample is large, even if the difference is only a few points on a 0-to-100 scale.</p>
<p>Researchers must inspect the group means and ask:</p>
<blockquote class="blockquote">
<p>Are these differences meaningful in the real world?</p>
</blockquote>
<p>ANOVA provides statistical evidence. Interpretation requires substantive judgment.</p>
<hr>
</section>
<section id="causality" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="causality"><span class="header-section-number">21.3</span> Causality</h2>
<p>ANOVA does not establish causality by itself.</p>
<p>If the data come from a randomized experiment, group differences may support causal claims.</p>
<p>If the data are observational, group differences may reflect confounding, selection, or other alternative explanations.</p>
<p>For example, if democracies have higher life expectancy than non-democracies, the difference may reflect wealth, health systems, education, colonial history, conflict, geography, or other factors.</p>
<p>ANOVA can help describe and test associations. Causal inference requires research design and theory.</p>
<hr>
</section>
</section>
<section id="key-terms" class="level1" data-number="22">
<h1 data-number="22"><span class="header-section-number">22</span> Key Terms</h1>
<p><strong>ANOVA</strong><br>
Analysis of variance; a method for comparing means across multiple groups.</p>
<p><strong>One-way ANOVA</strong><br>
ANOVA with one categorical independent variable.</p>
<p><strong>Two-way ANOVA</strong><br>
ANOVA with two categorical independent variables.</p>
<p><strong>Dependent variable</strong><br>
The interval-level outcome variable whose mean is compared across groups.</p>
<p><strong>Independent variable</strong><br>
A categorical variable used to define groups.</p>
<p><strong>Group mean</strong><br>
The mean of the dependent variable within a category.</p>
<p><strong>Grand mean</strong><br>
The overall mean of the dependent variable across all observations.</p>
<p><strong>Between-group variation</strong><br>
Variation in group means around the grand mean.</p>
<p><strong>Within-group variation</strong><br>
Variation of individual observations around their group means.</p>
<p><strong>Between sum of squares</strong><br>
A measure of variation explained by group differences.</p>
<p><strong>Within sum of squares</strong><br>
A measure of variation remaining within groups.</p>
<p><strong>Mean square between</strong><br>
Between sum of squares divided by between-group degrees of freedom.</p>
<p><strong>Mean square within</strong><br>
Within sum of squares divided by within-group degrees of freedom.</p>
<p><strong>F statistic</strong><br>
The ratio of between-group variance to within-group variance.</p>
<p><strong>F distribution</strong><br>
The probability distribution used to evaluate F statistics.</p>
<p><strong>Numerator degrees of freedom</strong><br>
Degrees of freedom associated with between-group variation.</p>
<p><strong>Denominator degrees of freedom</strong><br>
Degrees of freedom associated with within-group variation.</p>
<p><strong>Residual variation</strong><br>
Variation not explained by the group categories.</p>
<p><strong>R-squared</strong><br>
The proportion of total variation explained by the model.</p>
<p><strong>Post-hoc comparisons</strong><br>
Follow-up tests used to determine which specific group means differ after ANOVA rejects the null hypothesis.</p>
<hr>
</section>
<section id="chapter-summary" class="level1" data-number="23">
<h1 data-number="23"><span class="header-section-number">23</span> Chapter Summary</h1>
<p>ANOVA is used to compare more than two means simultaneously. It tests whether all group means are equal or whether at least one differs.</p>
<p>The logic of ANOVA is based on partitioning variance. Total variation in an interval-level outcome is divided into between-group variation and within-group variation. If group means differ substantially relative to variation within groups, the F statistic becomes large.</p>
<p>The F statistic is:</p>
<p><span class="math display">\[
F =
\frac{MS_{between}}{MS_{within}}
\]</span></p>
<p>A large F statistic with a small p-value leads us to reject the null hypothesis that all group means are equal.</p>
<p>One-way ANOVA uses one categorical independent variable. Two-way ANOVA uses two categorical independent variables and allows us to test whether each variable explains variation in the outcome after controlling for the other.</p>
<p>ANOVA can be useful for comparing means across groups, but it has limits. It does not identify which groups differ unless additional comparisons are performed. It does not establish causality unless supported by an appropriate research design. And in many applied settings, regression provides a more flexible framework.</p>
<p>The core lesson is that ANOVA helps us evaluate whether categorical group membership explains variation in an interval-level outcome. It extends the logic of difference-of-means tests to situations with multiple groups.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./chapter-11.html" class="pagination-link" aria-label="Chapter 11: Association Between Categorical Variables">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Chapter 11: Association Between Categorical Variables</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./chapter-13.html" class="pagination-link" aria-label="Chapter 13: Correlation">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Chapter 13: Correlation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>